module Increase
  module Resources
    class BeneficialOwners
      def retrieve: (
        String entity_beneficial_owner_id,
        ?request_options: Increase::request_opts
      ) -> Increase::EntityBeneficialOwner

      def update: (
        String entity_beneficial_owner_id,
        ?address: Increase::BeneficialOwnerUpdateParams::Address,
        ?confirmed_no_us_tax_id: bool,
        ?identification: Increase::BeneficialOwnerUpdateParams::Identification,
        ?name: String,
        ?request_options: Increase::request_opts
      ) -> Increase::EntityBeneficialOwner

      def list: (
        entity_id: String,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::EntityBeneficialOwner]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
