module Increase
  module Resources
    class CardDetails
      def update: (
        String card_id,
        pin: String,
        ?request_options: Increase::request_opts
      ) -> Increase::CardDetailsAPI

      def create_details_iframe: (
        String card_id,
        ?physical_card_id: String,
        ?request_options: Increase::request_opts
      ) -> Increase::CardIframeURL

      def details: (
        String card_id,
        ?request_options: Increase::request_opts
      ) -> Increase::CardDetailsAPI

      def initialize: (client: Increase::Client) -> void
    end
  end
end
