module Increase
  module Resources
    class LockboxAddresses
      def create: (
        ?description: String,
        ?request_options: Increase::request_opts
      ) -> Increase::LockboxAddress

      def retrieve: (
        String lockbox_address_id,
        ?request_options: Increase::request_opts
      ) -> Increase::LockboxAddress

      def update: (
        String lockbox_address_id,
        ?description: String,
        ?status: Increase::Models::LockboxAddressUpdateParams::status,
        ?request_options: Increase::request_opts
      ) -> Increase::LockboxAddress

      def list: (
        ?created_at: Increase::LockboxAddressListParams::CreatedAt,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::LockboxAddress]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
