module Increase
  module Resources
    class Simulations
      class CardPurchaseSupplements
        def create: (
          transaction_id: String,
          ?invoice: Increase::Simulations::CardPurchaseSupplementCreateParams::Invoice,
          ?line_items: ::Array[Increase::Simulations::CardPurchaseSupplementCreateParams::LineItem],
          ?request_options: Increase::request_opts
        ) -> Increase::CardPurchaseSupplement

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
