module Increase
  module Resources
    class Simulations
      class Exports
        def create: (
          category: Increase::Models::Simulations::ExportCreateParams::category,
          ?form_1099_int: Increase::Simulations::ExportCreateParams::Form1099Int,
          ?request_options: Increase::request_opts
        ) -> Increase::Export

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
