module Increase
  module Resources
    class Simulations
      class InboundWireTransfers
        def create: (
          account_number_id: String,
          amount: Integer,
          ?creditor_address_line1: String,
          ?creditor_address_line2: String,
          ?creditor_address_line3: String,
          ?creditor_name: String,
          ?debtor_address_line1: String,
          ?debtor_address_line2: String,
          ?debtor_address_line3: String,
          ?debtor_name: String,
          ?end_to_end_identification: String,
          ?instructing_agent_routing_number: String,
          ?instruction_identification: String,
          ?unique_end_to_end_transaction_reference: String,
          ?unstructured_remittance_information: String,
          ?wire_drawdown_request_id: String,
          ?request_options: Increase::request_opts
        ) -> Increase::InboundWireTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
