module Increase
  module Resources
    class Simulations
      class PendingTransactions
        def release_inbound_funds_hold: (
          String pending_transaction_id,
          ?request_options: Increase::request_opts
        ) -> Increase::PendingTransaction

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
