module Increase
  module Internal
    class Page[Elem]
      include Increase::Internal::Type::BasePage[Elem]

      attr_accessor data: top

      attr_accessor next_cursor: top

      def inspect: -> String
    end
  end
end
