# frozen_string_literal: true

module Increase
  module Models
    module Simulations
      # @see Increase::Resources::Simulations::CardAuthorizations#create
      class CardAuthorizationCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        # @!attribute amount
        #   The authorization amount in cents.
        #
        #   @return [Integer]
        required :amount, Integer

        # @!attribute authenticated_card_payment_id
        #   The identifier of a Card Payment with a `card_authentication` if you want to
        #   simulate an authenticated authorization.
        #
        #   @return [String, nil]
        optional :authenticated_card_payment_id, String

        # @!attribute card_id
        #   The identifier of the Card to be authorized.
        #
        #   @return [String, nil]
        optional :card_id, String

        # @!attribute decline_reason
        #   Forces a card decline with a specific reason. No real time decision will be
        #   sent.
        #
        #   @return [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::DeclineReason, nil]
        optional :decline_reason, enum: -> { Increase::Simulations::CardAuthorizationCreateParams::DeclineReason }

        # @!attribute digital_wallet_token_id
        #   The identifier of the Digital Wallet Token to be authorized.
        #
        #   @return [String, nil]
        optional :digital_wallet_token_id, String

        # @!attribute event_subscription_id
        #   The identifier of the Event Subscription to use. If provided, will override the
        #   default real time event subscription. Because you can only create one real time
        #   decision event subscription, you can use this field to route events to any
        #   specified event subscription for testing purposes.
        #
        #   @return [String, nil]
        optional :event_subscription_id, String

        # @!attribute merchant_acceptor_id
        #   The merchant identifier (commonly abbreviated as MID) of the merchant the card
        #   is transacting with.
        #
        #   @return [String, nil]
        optional :merchant_acceptor_id, String

        # @!attribute merchant_category_code
        #   The Merchant Category Code (commonly abbreviated as MCC) of the merchant the
        #   card is transacting with.
        #
        #   @return [String, nil]
        optional :merchant_category_code, String

        # @!attribute merchant_city
        #   The city the merchant resides in.
        #
        #   @return [String, nil]
        optional :merchant_city, String

        # @!attribute merchant_country
        #   The country the merchant resides in.
        #
        #   @return [String, nil]
        optional :merchant_country, String

        # @!attribute merchant_descriptor
        #   The merchant descriptor of the merchant the card is transacting with.
        #
        #   @return [String, nil]
        optional :merchant_descriptor, String

        # @!attribute merchant_state
        #   The state the merchant resides in.
        #
        #   @return [String, nil]
        optional :merchant_state, String

        # @!attribute network_details
        #   Fields specific to a given card network.
        #
        #   @return [Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails, nil]
        optional :network_details, -> { Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails }

        # @!attribute network_risk_score
        #   The risk score generated by the card network. For Visa this is the Visa Advanced
        #   Authorization risk score, from 0 to 99, where 99 is the riskiest.
        #
        #   @return [Integer, nil]
        optional :network_risk_score, Integer

        # @!attribute physical_card_id
        #   The identifier of the Physical Card to be authorized.
        #
        #   @return [String, nil]
        optional :physical_card_id, String

        # @!attribute processing_category
        #   Fields specific to a specific type of authorization, such as Automatic Fuel
        #   Dispensers, Refund Authorizations, or Cash Disbursements.
        #
        #   @return [Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory, nil]
        optional :processing_category,
                 -> { Increase::Simulations::CardAuthorizationCreateParams::ProcessingCategory }

        # @!attribute terminal_id
        #   The terminal identifier (commonly abbreviated as TID) of the terminal the card
        #   is transacting with.
        #
        #   @return [String, nil]
        optional :terminal_id, String

        # @!method initialize(amount:, authenticated_card_payment_id: nil, card_id: nil, decline_reason: nil, digital_wallet_token_id: nil, event_subscription_id: nil, merchant_acceptor_id: nil, merchant_category_code: nil, merchant_city: nil, merchant_country: nil, merchant_descriptor: nil, merchant_state: nil, network_details: nil, network_risk_score: nil, physical_card_id: nil, processing_category: nil, terminal_id: nil, request_options: {})
        #   @param amount [Integer] The authorization amount in cents.
        #
        #   @param authenticated_card_payment_id [String]
        #     The identifier of a Card Payment with a `card_authentication` if you want to
        #     simulate an authenticated authorization.
        #
        #   @param card_id [String] The identifier of the Card to be authorized.
        #
        #   @param decline_reason [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::DeclineReason]
        #     Forces a card decline with a specific reason. No real time decision will be
        #     sent.
        #
        #   @param digital_wallet_token_id [String] The identifier of the Digital Wallet Token to be authorized.
        #
        #   @param event_subscription_id [String]
        #     The identifier of the Event Subscription to use. If provided, will override the
        #     default real time event subscription. Because you can only create one real time
        #     decision event subscription, you can use this field to route events to any
        #     specified event subscription for testing purposes.
        #
        #   @param merchant_acceptor_id [String]
        #     The merchant identifier (commonly abbreviated as MID) of the merchant the card
        #     is transacting with.
        #
        #   @param merchant_category_code [String]
        #     The Merchant Category Code (commonly abbreviated as MCC) of the merchant the
        #     card is transacting with.
        #
        #   @param merchant_city [String] The city the merchant resides in.
        #
        #   @param merchant_country [String] The country the merchant resides in.
        #
        #   @param merchant_descriptor [String] The merchant descriptor of the merchant the card is transacting with.
        #
        #   @param merchant_state [String] The state the merchant resides in.
        #
        #   @param network_details [Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails]
        #     Fields specific to a given card network.
        #
        #   @param network_risk_score [Integer]
        #     The risk score generated by the card network. For Visa this is the Visa Advanced
        #     Authorization risk score, from 0 to 99, where 99 is the riskiest.
        #
        #   @param physical_card_id [String] The identifier of the Physical Card to be authorized.
        #
        #   @param processing_category [Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory]
        #     Fields specific to a specific type of authorization, such as Automatic Fuel
        #     Dispensers, Refund Authorizations, or Cash Disbursements.
        #
        #   @param terminal_id [String]
        #     The terminal identifier (commonly abbreviated as TID) of the terminal the card
        #     is transacting with.
        #
        #   @param request_options [Increase::RequestOptions, Hash{Symbol=>Object}]

        # Forces a card decline with a specific reason. No real time decision will be
        # sent.
        module DeclineReason
          extend Increase::Internal::Type::Enum

          # The account has been closed.
          ACCOUNT_CLOSED = :account_closed

          # The Card was not active.
          CARD_NOT_ACTIVE = :card_not_active

          # The Card has been canceled.
          CARD_CANCELED = :card_canceled

          # The Physical Card was not active.
          PHYSICAL_CARD_NOT_ACTIVE = :physical_card_not_active

          # The account's entity was not active.
          ENTITY_NOT_ACTIVE = :entity_not_active

          # The account was inactive.
          GROUP_LOCKED = :group_locked

          # The Card's Account did not have a sufficient available balance.
          INSUFFICIENT_FUNDS = :insufficient_funds

          # The given CVV2 did not match the card's value.
          CVV2_MISMATCH = :cvv2_mismatch

          # The given PIN did not match the card's value.
          PIN_MISMATCH = :pin_mismatch

          # The given expiration date did not match the card's value. Only applies when a CVV2 is present.
          CARD_EXPIRATION_MISMATCH = :card_expiration_mismatch

          # The attempted card transaction is not allowed per Increase's terms.
          TRANSACTION_NOT_ALLOWED = :transaction_not_allowed

          # The transaction was blocked by a limit or an authorization control.
          BREACHES_LIMIT = :breaches_limit

          # Your application declined the transaction via webhook.
          WEBHOOK_DECLINED = :webhook_declined

          # Your application webhook did not respond without the required timeout.
          WEBHOOK_TIMED_OUT = :webhook_timed_out

          # Declined by stand-in processing.
          DECLINED_BY_STAND_IN_PROCESSING = :declined_by_stand_in_processing

          # The card read had an invalid CVV or dCVV.
          INVALID_PHYSICAL_CARD = :invalid_physical_card

          # The original card authorization for this incremental authorization does not exist.
          MISSING_ORIGINAL_AUTHORIZATION = :missing_original_authorization

          # The card's authorization request cryptogram was invalid. The cryptogram can be from a physical card or a Digital Wallet Token purchase.
          INVALID_CRYPTOGRAM = :invalid_cryptogram

          # The transaction was declined because the 3DS authentication failed.
          FAILED_3DS_AUTHENTICATION = :failed_3ds_authentication

          # The transaction was suspected to be used by a card tester to test for valid card numbers.
          SUSPECTED_CARD_TESTING = :suspected_card_testing

          # The transaction was suspected to be fraudulent. Please reach out to support@increase.com for more information.
          SUSPECTED_FRAUD = :suspected_fraud

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        class NetworkDetails < Increase::Internal::Type::BaseModel
          # @!attribute visa
          #   Fields specific to the Visa network.
          #
          #   @return [Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa]
          required :visa, -> { Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa }

          # @!method initialize(visa:)
          #   Fields specific to a given card network.
          #
          #   @param visa [Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa]
          #     Fields specific to the Visa network.

          # @see Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails#visa
          class Visa < Increase::Internal::Type::BaseModel
            # @!attribute electronic_commerce_indicator
            #   For electronic commerce transactions, this identifies the level of security used
            #   in obtaining the customer's payment credential. For mail or telephone order
            #   transactions, identifies the type of mail or telephone order.
            #
            #   @return [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::ElectronicCommerceIndicator, nil]
            optional :electronic_commerce_indicator,
                     enum: -> { Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::ElectronicCommerceIndicator }

            # @!attribute point_of_service_entry_mode
            #   The method used to enter the cardholder's primary account number and card
            #   expiration date.
            #
            #   @return [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::PointOfServiceEntryMode, nil]
            optional :point_of_service_entry_mode,
                     enum: -> { Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::PointOfServiceEntryMode }

            # @!attribute stand_in_processing_reason
            #   The reason code for the stand-in processing.
            #
            #   @return [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::StandInProcessingReason, nil]
            optional :stand_in_processing_reason,
                     enum: -> { Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::StandInProcessingReason }

            # @!attribute terminal_entry_capability
            #   The capability of the terminal being used to read the card. Shows whether a
            #   terminal can e.g., accept chip cards or if it only supports magnetic stripe
            #   reads. This reflects the highest capability of the terminal — for example, a
            #   terminal that supports both chip and magnetic stripe will be identified as
            #   chip-capable.
            #
            #   @return [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::TerminalEntryCapability, nil]
            optional :terminal_entry_capability,
                     enum: -> { Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::TerminalEntryCapability }

            # @!method initialize(electronic_commerce_indicator: nil, point_of_service_entry_mode: nil, stand_in_processing_reason: nil, terminal_entry_capability: nil)
            #   Fields specific to the Visa network.
            #
            #   @param electronic_commerce_indicator [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::ElectronicCommerceIndicator]
            #     For electronic commerce transactions, this identifies the level of security used
            #     in obtaining the customer's payment credential. For mail or telephone order
            #     transactions, identifies the type of mail or telephone order.
            #
            #   @param point_of_service_entry_mode [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::PointOfServiceEntryMode]
            #     The method used to enter the cardholder's primary account number and card
            #     expiration date.
            #
            #   @param stand_in_processing_reason [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::StandInProcessingReason]
            #     The reason code for the stand-in processing.
            #
            #   @param terminal_entry_capability [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::TerminalEntryCapability]
            #     The capability of the terminal being used to read the card. Shows whether a
            #     terminal can e.g., accept chip cards or if it only supports magnetic stripe
            #     reads. This reflects the highest capability of the terminal — for example, a
            #     terminal that supports both chip and magnetic stripe will be identified as
            #     chip-capable.

            # For electronic commerce transactions, this identifies the level of security used
            # in obtaining the customer's payment credential. For mail or telephone order
            # transactions, identifies the type of mail or telephone order.
            #
            # @see Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa#electronic_commerce_indicator
            module ElectronicCommerceIndicator
              extend Increase::Internal::Type::Enum

              # Single transaction of a mail/phone order: Use to indicate that the transaction is a mail/phone order purchase, not a recurring transaction or installment payment. For domestic transactions in the US region, this value may also indicate one bill payment transaction in the card-present or card-absent environments.
              MAIL_PHONE_ORDER = :mail_phone_order

              # Recurring transaction: Payment indicator used to indicate a recurring transaction that originates from an acquirer in the US region.
              RECURRING = :recurring

              # Installment payment: Payment indicator used to indicate one purchase of goods or services that is billed to the account in multiple charges over a period of time agreed upon by the cardholder and merchant from transactions that originate from an acquirer in the US region.
              INSTALLMENT = :installment

              # Unknown classification: other mail order: Use to indicate that the type of mail/telephone order is unknown.
              UNKNOWN_MAIL_PHONE_ORDER = :unknown_mail_phone_order

              # Secure electronic commerce transaction: Use to indicate that the electronic commerce transaction has been authenticated using e.g., 3-D Secure
              SECURE_ELECTRONIC_COMMERCE = :secure_electronic_commerce

              # Non-authenticated security transaction at a 3-D Secure-capable merchant, and merchant attempted to authenticate the cardholder using 3-D Secure: Use to identify an electronic commerce transaction where the merchant attempted to authenticate the cardholder using 3-D Secure, but was unable to complete the authentication because the issuer or cardholder does not participate in the 3-D Secure program.
              NON_AUTHENTICATED_SECURITY_TRANSACTION_AT_3DS_CAPABLE_MERCHANT =
                :non_authenticated_security_transaction_at_3ds_capable_merchant

              # Non-authenticated security transaction: Use to identify an electronic commerce transaction that uses data encryption for security however, cardholder authentication is not performed using 3-D Secure.
              NON_AUTHENTICATED_SECURITY_TRANSACTION = :non_authenticated_security_transaction

              # Non-secure transaction: Use to identify an electronic commerce transaction that has no data protection.
              NON_SECURE_TRANSACTION = :non_secure_transaction

              # @!method self.values
              #   @return [Array<Symbol>]
            end

            # The method used to enter the cardholder's primary account number and card
            # expiration date.
            #
            # @see Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa#point_of_service_entry_mode
            module PointOfServiceEntryMode
              extend Increase::Internal::Type::Enum

              # Unknown
              UNKNOWN = :unknown

              # Manual key entry
              MANUAL = :manual

              # Magnetic stripe read, without card verification value
              MAGNETIC_STRIPE_NO_CVV = :magnetic_stripe_no_cvv

              # Optical code
              OPTICAL_CODE = :optical_code

              # Contact chip card
              INTEGRATED_CIRCUIT_CARD = :integrated_circuit_card

              # Contactless read of chip card
              CONTACTLESS = :contactless

              # Transaction initiated using a credential that has previously been stored on file
              CREDENTIAL_ON_FILE = :credential_on_file

              # Magnetic stripe read
              MAGNETIC_STRIPE = :magnetic_stripe

              # Contactless read of magnetic stripe data
              CONTACTLESS_MAGNETIC_STRIPE = :contactless_magnetic_stripe

              # Contact chip card, without card verification value
              INTEGRATED_CIRCUIT_CARD_NO_CVV = :integrated_circuit_card_no_cvv

              # @!method self.values
              #   @return [Array<Symbol>]
            end

            # The reason code for the stand-in processing.
            #
            # @see Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa#stand_in_processing_reason
            module StandInProcessingReason
              extend Increase::Internal::Type::Enum

              # Increase failed to process the authorization in a timely manner.
              ISSUER_ERROR = :issuer_error

              # The physical card read had an invalid CVV or dCVV.
              INVALID_PHYSICAL_CARD = :invalid_physical_card

              # The card's authorization request cryptogram was invalid. The cryptogram can be from a physical card or a Digital Wallet Token purchase.
              INVALID_CRYPTOGRAM = :invalid_cryptogram

              # The 3DS cardholder authentication verification value was invalid.
              INVALID_CARDHOLDER_AUTHENTICATION_VERIFICATION_VALUE =
                :invalid_cardholder_authentication_verification_value

              # An internal Visa error occurred. Visa uses this reason code for certain expected occurrences as well, such as Application Transaction Counter (ATC) replays.
              INTERNAL_VISA_ERROR = :internal_visa_error

              # The merchant has enabled Visa's Transaction Advisory Service and requires further authentication to perform the transaction. In practice this is often utilized at fuel pumps to tell the cardholder to see the cashier.
              MERCHANT_TRANSACTION_ADVISORY_SERVICE_AUTHENTICATION_REQUIRED =
                :merchant_transaction_advisory_service_authentication_required

              # The transaction was blocked by Visa's Payment Fraud Disruption service due to fraudulent Acquirer behavior, such as card testing.
              PAYMENT_FRAUD_DISRUPTION_ACQUIRER_BLOCK = :payment_fraud_disruption_acquirer_block

              # An unspecific reason for stand-in processing.
              OTHER = :other

              # @!method self.values
              #   @return [Array<Symbol>]
            end

            # The capability of the terminal being used to read the card. Shows whether a
            # terminal can e.g., accept chip cards or if it only supports magnetic stripe
            # reads. This reflects the highest capability of the terminal — for example, a
            # terminal that supports both chip and magnetic stripe will be identified as
            # chip-capable.
            #
            # @see Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa#terminal_entry_capability
            module TerminalEntryCapability
              extend Increase::Internal::Type::Enum

              # Unknown
              UNKNOWN = :unknown

              # No terminal was used for this transaction.
              TERMINAL_NOT_USED = :terminal_not_used

              # The terminal can only read magnetic stripes and does not have chip or contactless reading capability.
              MAGNETIC_STRIPE = :magnetic_stripe

              # The terminal can only read barcodes.
              BARCODE = :barcode

              # The terminal can only read cards via Optical Character Recognition.
              OPTICAL_CHARACTER_RECOGNITION = :optical_character_recognition

              # The terminal supports contact chip cards and can also read the magnetic stripe. If contact chip is supported, this value is used regardless of whether contactless is also supported.
              CHIP_OR_CONTACTLESS = :chip_or_contactless

              # The terminal supports contactless reads but does not support contact chip. Only used when the terminal lacks contact chip capability.
              CONTACTLESS_ONLY = :contactless_only

              # The terminal has no card reading capability.
              NO_CAPABILITY = :no_capability

              # @!method self.values
              #   @return [Array<Symbol>]
            end
          end
        end

        class ProcessingCategory < Increase::Internal::Type::BaseModel
          # @!attribute category
          #   The processing category describes the intent behind the authorization, such as
          #   whether it was used for bill payments or an automatic fuel dispenser.
          #
          #   @return [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory::Category]
          required :category,
                   enum: -> { Increase::Simulations::CardAuthorizationCreateParams::ProcessingCategory::Category }

          # @!attribute refund
          #   Details related to refund authorizations.
          #
          #   @return [Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory::Refund, nil]
          optional :refund, -> { Increase::Simulations::CardAuthorizationCreateParams::ProcessingCategory::Refund }

          # @!method initialize(category:, refund: nil)
          #   Fields specific to a specific type of authorization, such as Automatic Fuel
          #   Dispensers, Refund Authorizations, or Cash Disbursements.
          #
          #   @param category [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory::Category]
          #     The processing category describes the intent behind the authorization, such as
          #     whether it was used for bill payments or an automatic fuel dispenser.
          #
          #   @param refund [Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory::Refund]
          #     Details related to refund authorizations.

          # The processing category describes the intent behind the authorization, such as
          # whether it was used for bill payments or an automatic fuel dispenser.
          #
          # @see Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory#category
          module Category
            extend Increase::Internal::Type::Enum

            # Account funding transactions are transactions used to e.g., fund an account or transfer funds between accounts.
            ACCOUNT_FUNDING = :account_funding

            # Automatic fuel dispenser authorizations occur when a card is used at a gas pump, prior to the actual transaction amount being known. They are followed by an advice message that updates the amount of the pending transaction.
            AUTOMATIC_FUEL_DISPENSER = :automatic_fuel_dispenser

            # A transaction used to pay a bill.
            BILL_PAYMENT = :bill_payment

            # Original credit transactions are used to send money to a cardholder.
            ORIGINAL_CREDIT = :original_credit

            # A regular purchase.
            PURCHASE = :purchase

            # Quasi-cash transactions represent purchases of items which may be convertible to cash.
            QUASI_CASH = :quasi_cash

            # A refund card authorization, sometimes referred to as a credit voucher authorization, where funds are credited to the cardholder.
            REFUND = :refund

            # Cash disbursement transactions are used to withdraw cash from an ATM or a point of sale.
            CASH_DISBURSEMENT = :cash_disbursement

            # Cash deposit transactions are used to deposit cash at an ATM or a point of sale.
            CASH_DEPOSIT = :cash_deposit

            # A balance inquiry transaction is used to check the balance of an account associated with a card.
            BALANCE_INQUIRY = :balance_inquiry

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # @see Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory#refund
          class Refund < Increase::Internal::Type::BaseModel
            # @!attribute original_card_payment_id
            #   The card payment to link this refund to.
            #
            #   @return [String, nil]
            optional :original_card_payment_id, String

            # @!method initialize(original_card_payment_id: nil)
            #   Details related to refund authorizations.
            #
            #   @param original_card_payment_id [String] The card payment to link this refund to.
          end
        end
      end
    end
  end
end
