module Increase
  module Models
    type account =
      {
        id: String,
        account_revenue_rate: String?,
        bank: Increase::Models::Account::bank,
        closed_at: Time?,
        created_at: Time,
        currency: Increase::Models::Account::currency,
        entity_id: String,
        funding: Increase::Models::Account::funding?,
        idempotency_key: String?,
        informational_entity_id: String?,
        interest_accrued: String,
        interest_accrued_at: Date?,
        interest_rate: String,
        loan: Increase::Account::Loan?,
        name: String,
        program_id: String,
        status: Increase::Models::Account::status,
        type: Increase::Models::Account::type_
      }

    class Account < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor account_revenue_rate: String?

      attr_accessor bank: Increase::Models::Account::bank

      attr_accessor closed_at: Time?

      attr_accessor created_at: Time

      attr_accessor currency: Increase::Models::Account::currency

      attr_accessor entity_id: String

      attr_accessor funding: Increase::Models::Account::funding?

      attr_accessor idempotency_key: String?

      attr_accessor informational_entity_id: String?

      attr_accessor interest_accrued: String

      attr_accessor interest_accrued_at: Date?

      attr_accessor interest_rate: String

      attr_accessor loan: Increase::Account::Loan?

      attr_accessor name: String

      attr_accessor program_id: String

      attr_accessor status: Increase::Models::Account::status

      attr_accessor type: Increase::Models::Account::type_

      def initialize: (
        id: String,
        account_revenue_rate: String?,
        bank: Increase::Models::Account::bank,
        closed_at: Time?,
        created_at: Time,
        currency: Increase::Models::Account::currency,
        entity_id: String,
        funding: Increase::Models::Account::funding?,
        idempotency_key: String?,
        informational_entity_id: String?,
        interest_accrued: String,
        interest_accrued_at: Date?,
        interest_rate: String,
        loan: Increase::Account::Loan?,
        name: String,
        program_id: String,
        status: Increase::Models::Account::status,
        type: Increase::Models::Account::type_
      ) -> void

      def to_hash: -> {
        id: String,
        account_revenue_rate: String?,
        bank: Increase::Models::Account::bank,
        closed_at: Time?,
        created_at: Time,
        currency: Increase::Models::Account::currency,
        entity_id: String,
        funding: Increase::Models::Account::funding?,
        idempotency_key: String?,
        informational_entity_id: String?,
        interest_accrued: String,
        interest_accrued_at: Date?,
        interest_rate: String,
        loan: Increase::Account::Loan?,
        name: String,
        program_id: String,
        status: Increase::Models::Account::status,
        type: Increase::Models::Account::type_
      }

      type bank = :core_bank | :first_internet_bank | :grasshopper_bank

      module Bank
        extend Increase::Internal::Type::Enum

        # Core Bank
        CORE_BANK: :core_bank

        # First Internet Bank of Indiana
        FIRST_INTERNET_BANK: :first_internet_bank

        # Grasshopper Bank
        GRASSHOPPER_BANK: :grasshopper_bank

        def self?.values: -> ::Array[Increase::Models::Account::bank]
      end

      type currency = :USD

      module Currency
        extend Increase::Internal::Type::Enum

        # US Dollar (USD)
        USD: :USD

        def self?.values: -> ::Array[Increase::Models::Account::currency]
      end

      type funding = :loan | :deposits

      module Funding
        extend Increase::Internal::Type::Enum

        # An account funded by a loan. Before opening a loan account, contact support@increase.com to set up a loan program.
        LOAN: :loan

        # An account funded by deposits.
        DEPOSITS: :deposits

        def self?.values: -> ::Array[Increase::Models::Account::funding]
      end

      type loan =
        {
          credit_limit: Integer,
          grace_period_days: Integer,
          maturity_date: Date?,
          statement_day_of_month: Integer,
          statement_payment_type: Increase::Models::Account::Loan::statement_payment_type
        }

      class Loan < Increase::Internal::Type::BaseModel
        attr_accessor credit_limit: Integer

        attr_accessor grace_period_days: Integer

        attr_accessor maturity_date: Date?

        attr_accessor statement_day_of_month: Integer

        attr_accessor statement_payment_type: Increase::Models::Account::Loan::statement_payment_type

        def initialize: (
          credit_limit: Integer,
          grace_period_days: Integer,
          maturity_date: Date?,
          statement_day_of_month: Integer,
          statement_payment_type: Increase::Models::Account::Loan::statement_payment_type
        ) -> void

        def to_hash: -> {
          credit_limit: Integer,
          grace_period_days: Integer,
          maturity_date: Date?,
          statement_day_of_month: Integer,
          statement_payment_type: Increase::Models::Account::Loan::statement_payment_type
        }

        type statement_payment_type = :balance | :interest_until_maturity

        module StatementPaymentType
          extend Increase::Internal::Type::Enum

          # The borrower must pay the full balance of the loan at the end of the statement period.
          BALANCE: :balance

          # The borrower must pay the accrued interest at the end of the statement period.
          INTEREST_UNTIL_MATURITY: :interest_until_maturity

          def self?.values: -> ::Array[Increase::Models::Account::Loan::statement_payment_type]
        end
      end

      type status = :closed | :open

      module Status
        extend Increase::Internal::Type::Enum

        # Closed Accounts on which no new activity can occur.
        CLOSED: :closed

        # Open Accounts that are ready to use.
        OPEN: :open

        def self?.values: -> ::Array[Increase::Models::Account::status]
      end

      type type_ = :account

      module Type
        extend Increase::Internal::Type::Enum

        ACCOUNT: :account

        def self?.values: -> ::Array[Increase::Models::Account::type_]
      end
    end
  end
end
