module Increase
  module Models
    type ach_transfer_list_response =
      { data: ::Array[Increase::ACHTransfer], next_cursor: String? }

    class ACHTransferListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::ACHTransfer]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::ACHTransfer],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[Increase::ACHTransfer],
        next_cursor: String?
      }
    end
  end
end
