module Increase
  module Models
    type bookkeeping_account_update_params =
      { bookkeeping_account_id: String, name: String }
      & Increase::Internal::Type::request_parameters

    class BookkeepingAccountUpdateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor bookkeeping_account_id: String

      attr_accessor name: String

      def initialize: (
        bookkeeping_account_id: String,
        name: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        bookkeeping_account_id: String,
        name: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
