module Increase
  module Models
    type bookkeeping_entry_set_retrieve_params =
      { bookkeeping_entry_set_id: String }
      & Increase::Internal::Type::request_parameters

    class BookkeepingEntrySetRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor bookkeeping_entry_set_id: String

      def initialize: (
        bookkeeping_entry_set_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        bookkeeping_entry_set_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
