module Increase
  module Models
    type bookkeeping_account_list_response =
      { data: ::Array[Increase::BookkeepingAccount], next_cursor: String? }

    class BookkeepingAccountListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::BookkeepingAccount]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::BookkeepingAccount],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[Increase::BookkeepingAccount],
        next_cursor: String?
      }
    end
  end
end
