module Increase
  module Models
    type bookkeeping_entry_list_response =
      { data: ::Array[Increase::BookkeepingEntry], next_cursor: String? }

    class BookkeepingEntryListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::BookkeepingEntry]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::BookkeepingEntry],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[Increase::BookkeepingEntry],
        next_cursor: String?
      }
    end
  end
end
