module Increase
  module Models
    type card_push_transfer_create_params =
      {
        amount: Integer,
        business_application_identifier: Increase::Models::CardPushTransferCreateParams::business_application_identifier,
        card_token_id: String,
        merchant_category_code: String,
        merchant_city_name: String,
        merchant_name: String,
        merchant_name_prefix: String,
        merchant_postal_code: String,
        merchant_state: String,
        recipient_name: String,
        sender_address_city: String,
        :sender_address_line1 => String,
        sender_address_postal_code: String,
        sender_address_state: String,
        sender_name: String,
        source_account_number_id: String,
        require_approval: bool
      }
      & Increase::Internal::Type::request_parameters

    class CardPushTransferCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor amount: Integer

      attr_accessor business_application_identifier: Increase::Models::CardPushTransferCreateParams::business_application_identifier

      attr_accessor card_token_id: String

      attr_accessor merchant_category_code: String

      attr_accessor merchant_city_name: String

      attr_accessor merchant_name: String

      attr_accessor merchant_name_prefix: String

      attr_accessor merchant_postal_code: String

      attr_accessor merchant_state: String

      attr_accessor recipient_name: String

      attr_accessor sender_address_city: String

      attr_accessor sender_address_line1: String

      attr_accessor sender_address_postal_code: String

      attr_accessor sender_address_state: String

      attr_accessor sender_name: String

      attr_accessor source_account_number_id: String

      attr_reader require_approval: bool?

      def require_approval=: (bool) -> bool

      def initialize: (
        amount: Integer,
        business_application_identifier: Increase::Models::CardPushTransferCreateParams::business_application_identifier,
        card_token_id: String,
        merchant_category_code: String,
        merchant_city_name: String,
        merchant_name: String,
        merchant_name_prefix: String,
        merchant_postal_code: String,
        merchant_state: String,
        recipient_name: String,
        sender_address_city: String,
        sender_address_line1: String,
        sender_address_postal_code: String,
        sender_address_state: String,
        sender_name: String,
        source_account_number_id: String,
        ?require_approval: bool,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        amount: Integer,
        business_application_identifier: Increase::Models::CardPushTransferCreateParams::business_application_identifier,
        card_token_id: String,
        merchant_category_code: String,
        merchant_city_name: String,
        merchant_name: String,
        merchant_name_prefix: String,
        merchant_postal_code: String,
        merchant_state: String,
        recipient_name: String,
        sender_address_city: String,
        :sender_address_line1 => String,
        sender_address_postal_code: String,
        sender_address_state: String,
        sender_name: String,
        source_account_number_id: String,
        require_approval: bool,
        request_options: Increase::RequestOptions
      }

      type business_application_identifier =
        :account_to_account
        | :business_to_business
        | :money_transfer_bank_initiated
        | :non_card_bill_payment
        | :consumer_bill_payment
        | :card_bill_payment
        | :funds_disbursement
        | :funds_transfer
        | :loyalty_and_offers
        | :merchant_disbursement
        | :merchant_payment
        | :person_to_person
        | :top_up
        | :wallet_transfer

      module BusinessApplicationIdentifier
        extend Increase::Internal::Type::Enum

        # Account to Account
        ACCOUNT_TO_ACCOUNT: :account_to_account

        # Business to Business
        BUSINESS_TO_BUSINESS: :business_to_business

        # Money Transfer Bank Initiated
        MONEY_TRANSFER_BANK_INITIATED: :money_transfer_bank_initiated

        # Non-Card Bill Payment
        NON_CARD_BILL_PAYMENT: :non_card_bill_payment

        # Consumer Bill Payment
        CONSUMER_BILL_PAYMENT: :consumer_bill_payment

        # Card Bill Payment
        CARD_BILL_PAYMENT: :card_bill_payment

        # Funds Disbursement
        FUNDS_DISBURSEMENT: :funds_disbursement

        # Funds Transfer
        FUNDS_TRANSFER: :funds_transfer

        # Loyalty and Offers
        LOYALTY_AND_OFFERS: :loyalty_and_offers

        # Merchant Disbursement
        MERCHANT_DISBURSEMENT: :merchant_disbursement

        # Merchant Payment
        MERCHANT_PAYMENT: :merchant_payment

        # Person to Person
        PERSON_TO_PERSON: :person_to_person

        # Top Up
        TOP_UP: :top_up

        # Wallet Transfer
        WALLET_TRANSFER: :wallet_transfer

        def self?.values: -> ::Array[Increase::Models::CardPushTransferCreateParams::business_application_identifier]
      end
    end
  end
end
