module Increase
  module Models
    type card_list_response =
      { data: ::Array[Increase::Card], next_cursor: String? }

    class CardListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::Card]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::Card],
        next_cursor: String?
      ) -> void

      def to_hash: -> { data: ::Array[Increase::Card], next_cursor: String? }
    end
  end
end
