module Increase
  module Models
    type card =
      {
        id: String,
        account_id: String,
        authorization_controls: Increase::Card::AuthorizationControls?,
        billing_address: Increase::Card::BillingAddress,
        created_at: Time,
        description: String?,
        digital_wallet: Increase::Card::DigitalWallet?,
        entity_id: String?,
        expiration_month: Integer,
        expiration_year: Integer,
        idempotency_key: String?,
        :last4 => String,
        status: Increase::Models::Card::status,
        type: Increase::Models::Card::type_
      }

    class Card < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor account_id: String

      attr_accessor authorization_controls: Increase::Card::AuthorizationControls?

      attr_accessor billing_address: Increase::Card::BillingAddress

      attr_accessor created_at: Time

      attr_accessor description: String?

      attr_accessor digital_wallet: Increase::Card::DigitalWallet?

      attr_accessor entity_id: String?

      attr_accessor expiration_month: Integer

      attr_accessor expiration_year: Integer

      attr_accessor idempotency_key: String?

      attr_accessor last4: String

      attr_accessor status: Increase::Models::Card::status

      attr_accessor type: Increase::Models::Card::type_

      def initialize: (
        id: String,
        account_id: String,
        authorization_controls: Increase::Card::AuthorizationControls?,
        billing_address: Increase::Card::BillingAddress,
        created_at: Time,
        description: String?,
        digital_wallet: Increase::Card::DigitalWallet?,
        entity_id: String?,
        expiration_month: Integer,
        expiration_year: Integer,
        idempotency_key: String?,
        last4: String,
        status: Increase::Models::Card::status,
        type: Increase::Models::Card::type_
      ) -> void

      def to_hash: -> {
        id: String,
        account_id: String,
        authorization_controls: Increase::Card::AuthorizationControls?,
        billing_address: Increase::Card::BillingAddress,
        created_at: Time,
        description: String?,
        digital_wallet: Increase::Card::DigitalWallet?,
        entity_id: String?,
        expiration_month: Integer,
        expiration_year: Integer,
        idempotency_key: String?,
        :last4 => String,
        status: Increase::Models::Card::status,
        type: Increase::Models::Card::type_
      }

      type authorization_controls =
        {
          merchant_acceptor_identifier: Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier?,
          merchant_category_code: Increase::Card::AuthorizationControls::MerchantCategoryCode?,
          merchant_country: Increase::Card::AuthorizationControls::MerchantCountry?,
          usage: Increase::Card::AuthorizationControls::Usage?
        }

      class AuthorizationControls < Increase::Internal::Type::BaseModel
        attr_accessor merchant_acceptor_identifier: Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier?

        attr_accessor merchant_category_code: Increase::Card::AuthorizationControls::MerchantCategoryCode?

        attr_accessor merchant_country: Increase::Card::AuthorizationControls::MerchantCountry?

        attr_accessor usage: Increase::Card::AuthorizationControls::Usage?

        def initialize: (
          merchant_acceptor_identifier: Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier?,
          merchant_category_code: Increase::Card::AuthorizationControls::MerchantCategoryCode?,
          merchant_country: Increase::Card::AuthorizationControls::MerchantCountry?,
          usage: Increase::Card::AuthorizationControls::Usage?
        ) -> void

        def to_hash: -> {
          merchant_acceptor_identifier: Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier?,
          merchant_category_code: Increase::Card::AuthorizationControls::MerchantCategoryCode?,
          merchant_country: Increase::Card::AuthorizationControls::MerchantCountry?,
          usage: Increase::Card::AuthorizationControls::Usage?
        }

        type merchant_acceptor_identifier =
          {
            allowed: ::Array[Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier::Allowed]?,
            blocked: ::Array[Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]?
          }

        class MerchantAcceptorIdentifier < Increase::Internal::Type::BaseModel
          attr_accessor allowed: ::Array[Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier::Allowed]?

          attr_accessor blocked: ::Array[Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]?

          def initialize: (
            allowed: ::Array[Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier::Allowed]?,
            blocked: ::Array[Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]?
          ) -> void

          def to_hash: -> {
            allowed: ::Array[Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier::Allowed]?,
            blocked: ::Array[Increase::Card::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]?
          }

          type allowed = { identifier: String }

          class Allowed < Increase::Internal::Type::BaseModel
            attr_accessor identifier: String

            def initialize: (identifier: String) -> void

            def to_hash: -> { identifier: String }
          end

          type blocked = { identifier: String }

          class Blocked < Increase::Internal::Type::BaseModel
            attr_accessor identifier: String

            def initialize: (identifier: String) -> void

            def to_hash: -> { identifier: String }
          end
        end

        type merchant_category_code =
          {
            allowed: ::Array[Increase::Card::AuthorizationControls::MerchantCategoryCode::Allowed]?,
            blocked: ::Array[Increase::Card::AuthorizationControls::MerchantCategoryCode::Blocked]?
          }

        class MerchantCategoryCode < Increase::Internal::Type::BaseModel
          attr_accessor allowed: ::Array[Increase::Card::AuthorizationControls::MerchantCategoryCode::Allowed]?

          attr_accessor blocked: ::Array[Increase::Card::AuthorizationControls::MerchantCategoryCode::Blocked]?

          def initialize: (
            allowed: ::Array[Increase::Card::AuthorizationControls::MerchantCategoryCode::Allowed]?,
            blocked: ::Array[Increase::Card::AuthorizationControls::MerchantCategoryCode::Blocked]?
          ) -> void

          def to_hash: -> {
            allowed: ::Array[Increase::Card::AuthorizationControls::MerchantCategoryCode::Allowed]?,
            blocked: ::Array[Increase::Card::AuthorizationControls::MerchantCategoryCode::Blocked]?
          }

          type allowed = { code: String }

          class Allowed < Increase::Internal::Type::BaseModel
            attr_accessor code: String

            def initialize: (code: String) -> void

            def to_hash: -> { code: String }
          end

          type blocked = { code: String }

          class Blocked < Increase::Internal::Type::BaseModel
            attr_accessor code: String

            def initialize: (code: String) -> void

            def to_hash: -> { code: String }
          end
        end

        type merchant_country =
          {
            allowed: ::Array[Increase::Card::AuthorizationControls::MerchantCountry::Allowed]?,
            blocked: ::Array[Increase::Card::AuthorizationControls::MerchantCountry::Blocked]?
          }

        class MerchantCountry < Increase::Internal::Type::BaseModel
          attr_accessor allowed: ::Array[Increase::Card::AuthorizationControls::MerchantCountry::Allowed]?

          attr_accessor blocked: ::Array[Increase::Card::AuthorizationControls::MerchantCountry::Blocked]?

          def initialize: (
            allowed: ::Array[Increase::Card::AuthorizationControls::MerchantCountry::Allowed]?,
            blocked: ::Array[Increase::Card::AuthorizationControls::MerchantCountry::Blocked]?
          ) -> void

          def to_hash: -> {
            allowed: ::Array[Increase::Card::AuthorizationControls::MerchantCountry::Allowed]?,
            blocked: ::Array[Increase::Card::AuthorizationControls::MerchantCountry::Blocked]?
          }

          type allowed = { country: String }

          class Allowed < Increase::Internal::Type::BaseModel
            attr_accessor country: String

            def initialize: (country: String) -> void

            def to_hash: -> { country: String }
          end

          type blocked = { country: String }

          class Blocked < Increase::Internal::Type::BaseModel
            attr_accessor country: String

            def initialize: (country: String) -> void

            def to_hash: -> { country: String }
          end
        end

        type usage =
          {
            category: Increase::Models::Card::AuthorizationControls::Usage::category,
            multi_use: Increase::Card::AuthorizationControls::Usage::MultiUse?,
            single_use: Increase::Card::AuthorizationControls::Usage::SingleUse?
          }

        class Usage < Increase::Internal::Type::BaseModel
          attr_accessor category: Increase::Models::Card::AuthorizationControls::Usage::category

          attr_accessor multi_use: Increase::Card::AuthorizationControls::Usage::MultiUse?

          attr_accessor single_use: Increase::Card::AuthorizationControls::Usage::SingleUse?

          def initialize: (
            category: Increase::Models::Card::AuthorizationControls::Usage::category,
            multi_use: Increase::Card::AuthorizationControls::Usage::MultiUse?,
            single_use: Increase::Card::AuthorizationControls::Usage::SingleUse?
          ) -> void

          def to_hash: -> {
            category: Increase::Models::Card::AuthorizationControls::Usage::category,
            multi_use: Increase::Card::AuthorizationControls::Usage::MultiUse?,
            single_use: Increase::Card::AuthorizationControls::Usage::SingleUse?
          }

          type category = :single_use | :multi_use

          module Category
            extend Increase::Internal::Type::Enum

            # The card can only be used for a single authorization.
            SINGLE_USE: :single_use

            # The card can be used for multiple authorizations.
            MULTI_USE: :multi_use

            def self?.values: -> ::Array[Increase::Models::Card::AuthorizationControls::Usage::category]
          end

          type multi_use =
            {
              spending_limits: ::Array[Increase::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit]?
            }

          class MultiUse < Increase::Internal::Type::BaseModel
            attr_accessor spending_limits: ::Array[Increase::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit]?

            def initialize: (
              spending_limits: ::Array[Increase::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit]?
            ) -> void

            def to_hash: -> {
              spending_limits: ::Array[Increase::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit]?
            }

            type spending_limit =
              {
                interval: Increase::Models::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval,
                merchant_category_codes: ::Array[Increase::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]?,
                settlement_amount: Integer
              }

            class SpendingLimit < Increase::Internal::Type::BaseModel
              attr_accessor interval: Increase::Models::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval

              attr_accessor merchant_category_codes: ::Array[Increase::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]?

              attr_accessor settlement_amount: Integer

              def initialize: (
                interval: Increase::Models::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval,
                merchant_category_codes: ::Array[Increase::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]?,
                settlement_amount: Integer
              ) -> void

              def to_hash: -> {
                interval: Increase::Models::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval,
                merchant_category_codes: ::Array[Increase::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]?,
                settlement_amount: Integer
              }

              type interval =
                :all_time | :per_transaction | :per_day | :per_week | :per_month

              module Interval
                extend Increase::Internal::Type::Enum

                # The spending limit applies over the lifetime of the card.
                ALL_TIME: :all_time

                # The spending limit applies per transaction.
                PER_TRANSACTION: :per_transaction

                # The spending limit applies per day. Resets nightly at midnight UTC.
                PER_DAY: :per_day

                # The spending limit applies per week. Resets weekly on Mondays at midnight UTC.
                PER_WEEK: :per_week

                # The spending limit applies per month. Resets on the first of the month, midnight UTC.
                PER_MONTH: :per_month

                def self?.values: -> ::Array[Increase::Models::Card::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval]
              end

              type merchant_category_code = { code: String }

              class MerchantCategoryCode < Increase::Internal::Type::BaseModel
                attr_accessor code: String

                def initialize: (code: String) -> void

                def to_hash: -> { code: String }
              end
            end
          end

          type single_use =
            {
              settlement_amount: Increase::Card::AuthorizationControls::Usage::SingleUse::SettlementAmount
            }

          class SingleUse < Increase::Internal::Type::BaseModel
            attr_accessor settlement_amount: Increase::Card::AuthorizationControls::Usage::SingleUse::SettlementAmount

            def initialize: (
              settlement_amount: Increase::Card::AuthorizationControls::Usage::SingleUse::SettlementAmount
            ) -> void

            def to_hash: -> {
              settlement_amount: Increase::Card::AuthorizationControls::Usage::SingleUse::SettlementAmount
            }

            type settlement_amount =
              {
                comparison: Increase::Models::Card::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison,
                value: Integer
              }

            class SettlementAmount < Increase::Internal::Type::BaseModel
              attr_accessor comparison: Increase::Models::Card::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison

              attr_accessor value: Integer

              def initialize: (
                comparison: Increase::Models::Card::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison,
                value: Integer
              ) -> void

              def to_hash: -> {
                comparison: Increase::Models::Card::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison,
                value: Integer
              }

              type comparison = :equals | :less_than_or_equals

              module Comparison
                extend Increase::Internal::Type::Enum

                # The settlement amount must be exactly the specified value.
                EQUALS: :equals

                # The settlement amount must be less than or equal to the specified value.
                LESS_THAN_OR_EQUALS: :less_than_or_equals

                def self?.values: -> ::Array[Increase::Models::Card::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison]
              end
            end
          end
        end
      end

      type billing_address =
        {
          city: String?,
          :line1 => String?,
          :line2 => String?,
          postal_code: String?,
          state: String?
        }

      class BillingAddress < Increase::Internal::Type::BaseModel
        attr_accessor city: String?

        attr_accessor line1: String?

        attr_accessor line2: String?

        attr_accessor postal_code: String?

        attr_accessor state: String?

        def initialize: (
          city: String?,
          line1: String?,
          line2: String?,
          postal_code: String?,
          state: String?
        ) -> void

        def to_hash: -> {
          city: String?,
          :line1 => String?,
          :line2 => String?,
          postal_code: String?,
          state: String?
        }
      end

      type digital_wallet =
        { digital_card_profile_id: String?, email: String?, phone: String? }

      class DigitalWallet < Increase::Internal::Type::BaseModel
        attr_accessor digital_card_profile_id: String?

        attr_accessor email: String?

        attr_accessor phone: String?

        def initialize: (
          digital_card_profile_id: String?,
          email: String?,
          phone: String?
        ) -> void

        def to_hash: -> {
          digital_card_profile_id: String?,
          email: String?,
          phone: String?
        }
      end

      type status = :active | :disabled | :canceled

      module Status
        extend Increase::Internal::Type::Enum

        # The card is active.
        ACTIVE: :active

        # The card is temporarily disabled.
        DISABLED: :disabled

        # The card is permanently canceled.
        CANCELED: :canceled

        def self?.values: -> ::Array[Increase::Models::Card::status]
      end

      type type_ = :card

      module Type
        extend Increase::Internal::Type::Enum

        CARD: :card

        def self?.values: -> ::Array[Increase::Models::Card::type_]
      end
    end
  end
end
