module Increase
  module Models
    type card_create_params =
      {
        account_id: String,
        authorization_controls: Increase::CardCreateParams::AuthorizationControls,
        billing_address: Increase::CardCreateParams::BillingAddress,
        description: String,
        digital_wallet: Increase::CardCreateParams::DigitalWallet,
        entity_id: String
      }
      & Increase::Internal::Type::request_parameters

    class CardCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_reader authorization_controls: Increase::CardCreateParams::AuthorizationControls?

      def authorization_controls=: (
        Increase::CardCreateParams::AuthorizationControls
      ) -> Increase::CardCreateParams::AuthorizationControls

      attr_reader billing_address: Increase::CardCreateParams::BillingAddress?

      def billing_address=: (
        Increase::CardCreateParams::BillingAddress
      ) -> Increase::CardCreateParams::BillingAddress

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader digital_wallet: Increase::CardCreateParams::DigitalWallet?

      def digital_wallet=: (
        Increase::CardCreateParams::DigitalWallet
      ) -> Increase::CardCreateParams::DigitalWallet

      attr_reader entity_id: String?

      def entity_id=: (String) -> String

      def initialize: (
        account_id: String,
        ?authorization_controls: Increase::CardCreateParams::AuthorizationControls,
        ?billing_address: Increase::CardCreateParams::BillingAddress,
        ?description: String,
        ?digital_wallet: Increase::CardCreateParams::DigitalWallet,
        ?entity_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        authorization_controls: Increase::CardCreateParams::AuthorizationControls,
        billing_address: Increase::CardCreateParams::BillingAddress,
        description: String,
        digital_wallet: Increase::CardCreateParams::DigitalWallet,
        entity_id: String,
        request_options: Increase::RequestOptions
      }

      type authorization_controls =
        {
          merchant_acceptor_identifier: Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier,
          merchant_category_code: Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode,
          merchant_country: Increase::CardCreateParams::AuthorizationControls::MerchantCountry,
          usage: Increase::CardCreateParams::AuthorizationControls::Usage
        }

      class AuthorizationControls < Increase::Internal::Type::BaseModel
        attr_reader merchant_acceptor_identifier: Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier?

        def merchant_acceptor_identifier=: (
          Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier
        ) -> Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier

        attr_reader merchant_category_code: Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode?

        def merchant_category_code=: (
          Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode
        ) -> Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode

        attr_reader merchant_country: Increase::CardCreateParams::AuthorizationControls::MerchantCountry?

        def merchant_country=: (
          Increase::CardCreateParams::AuthorizationControls::MerchantCountry
        ) -> Increase::CardCreateParams::AuthorizationControls::MerchantCountry

        attr_reader usage: Increase::CardCreateParams::AuthorizationControls::Usage?

        def usage=: (
          Increase::CardCreateParams::AuthorizationControls::Usage
        ) -> Increase::CardCreateParams::AuthorizationControls::Usage

        def initialize: (
          ?merchant_acceptor_identifier: Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier,
          ?merchant_category_code: Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode,
          ?merchant_country: Increase::CardCreateParams::AuthorizationControls::MerchantCountry,
          ?usage: Increase::CardCreateParams::AuthorizationControls::Usage
        ) -> void

        def to_hash: -> {
          merchant_acceptor_identifier: Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier,
          merchant_category_code: Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode,
          merchant_country: Increase::CardCreateParams::AuthorizationControls::MerchantCountry,
          usage: Increase::CardCreateParams::AuthorizationControls::Usage
        }

        type merchant_acceptor_identifier =
          {
            allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Allowed],
            blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]
          }

        class MerchantAcceptorIdentifier < Increase::Internal::Type::BaseModel
          attr_reader allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Allowed]?

          def allowed=: (
            ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Allowed]
          ) -> ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Allowed]

          attr_reader blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]?

          def blocked=: (
            ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]
          ) -> ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]

          def initialize: (
            ?allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Allowed],
            ?blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]
          ) -> void

          def to_hash: -> {
            allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Allowed],
            blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantAcceptorIdentifier::Blocked]
          }

          type allowed = { identifier: String }

          class Allowed < Increase::Internal::Type::BaseModel
            attr_accessor identifier: String

            def initialize: (identifier: String) -> void

            def to_hash: -> { identifier: String }
          end

          type blocked = { identifier: String }

          class Blocked < Increase::Internal::Type::BaseModel
            attr_accessor identifier: String

            def initialize: (identifier: String) -> void

            def to_hash: -> { identifier: String }
          end
        end

        type merchant_category_code =
          {
            allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Allowed],
            blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Blocked]
          }

        class MerchantCategoryCode < Increase::Internal::Type::BaseModel
          attr_reader allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Allowed]?

          def allowed=: (
            ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Allowed]
          ) -> ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Allowed]

          attr_reader blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Blocked]?

          def blocked=: (
            ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Blocked]
          ) -> ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Blocked]

          def initialize: (
            ?allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Allowed],
            ?blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Blocked]
          ) -> void

          def to_hash: -> {
            allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Allowed],
            blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCategoryCode::Blocked]
          }

          type allowed = { code: String }

          class Allowed < Increase::Internal::Type::BaseModel
            attr_accessor code: String

            def initialize: (code: String) -> void

            def to_hash: -> { code: String }
          end

          type blocked = { code: String }

          class Blocked < Increase::Internal::Type::BaseModel
            attr_accessor code: String

            def initialize: (code: String) -> void

            def to_hash: -> { code: String }
          end
        end

        type merchant_country =
          {
            allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Allowed],
            blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Blocked]
          }

        class MerchantCountry < Increase::Internal::Type::BaseModel
          attr_reader allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Allowed]?

          def allowed=: (
            ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Allowed]
          ) -> ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Allowed]

          attr_reader blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Blocked]?

          def blocked=: (
            ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Blocked]
          ) -> ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Blocked]

          def initialize: (
            ?allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Allowed],
            ?blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Blocked]
          ) -> void

          def to_hash: -> {
            allowed: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Allowed],
            blocked: ::Array[Increase::CardCreateParams::AuthorizationControls::MerchantCountry::Blocked]
          }

          type allowed = { country: String }

          class Allowed < Increase::Internal::Type::BaseModel
            attr_accessor country: String

            def initialize: (country: String) -> void

            def to_hash: -> { country: String }
          end

          type blocked = { country: String }

          class Blocked < Increase::Internal::Type::BaseModel
            attr_accessor country: String

            def initialize: (country: String) -> void

            def to_hash: -> { country: String }
          end
        end

        type usage =
          {
            category: Increase::Models::CardCreateParams::AuthorizationControls::Usage::category,
            multi_use: Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse,
            single_use: Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse
          }

        class Usage < Increase::Internal::Type::BaseModel
          attr_accessor category: Increase::Models::CardCreateParams::AuthorizationControls::Usage::category

          attr_reader multi_use: Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse?

          def multi_use=: (
            Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse
          ) -> Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse

          attr_reader single_use: Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse?

          def single_use=: (
            Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse
          ) -> Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse

          def initialize: (
            category: Increase::Models::CardCreateParams::AuthorizationControls::Usage::category,
            ?multi_use: Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse,
            ?single_use: Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse
          ) -> void

          def to_hash: -> {
            category: Increase::Models::CardCreateParams::AuthorizationControls::Usage::category,
            multi_use: Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse,
            single_use: Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse
          }

          type category = :single_use | :multi_use

          module Category
            extend Increase::Internal::Type::Enum

            # The card can only be used for a single authorization.
            SINGLE_USE: :single_use

            # The card can be used for multiple authorizations.
            MULTI_USE: :multi_use

            def self?.values: -> ::Array[Increase::Models::CardCreateParams::AuthorizationControls::Usage::category]
          end

          type multi_use =
            {
              spending_limits: ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit]
            }

          class MultiUse < Increase::Internal::Type::BaseModel
            attr_reader spending_limits: ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit]?

            def spending_limits=: (
              ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit]
            ) -> ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit]

            def initialize: (
              ?spending_limits: ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit]
            ) -> void

            def to_hash: -> {
              spending_limits: ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit]
            }

            type spending_limit =
              {
                interval: Increase::Models::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval,
                settlement_amount: Integer,
                merchant_category_codes: ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]
              }

            class SpendingLimit < Increase::Internal::Type::BaseModel
              attr_accessor interval: Increase::Models::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval

              attr_accessor settlement_amount: Integer

              attr_reader merchant_category_codes: ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]?

              def merchant_category_codes=: (
                ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]
              ) -> ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]

              def initialize: (
                interval: Increase::Models::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval,
                settlement_amount: Integer,
                ?merchant_category_codes: ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]
              ) -> void

              def to_hash: -> {
                interval: Increase::Models::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval,
                settlement_amount: Integer,
                merchant_category_codes: ::Array[Increase::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::MerchantCategoryCode]
              }

              type interval =
                :all_time | :per_transaction | :per_day | :per_week | :per_month

              module Interval
                extend Increase::Internal::Type::Enum

                # The spending limit applies over the lifetime of the card.
                ALL_TIME: :all_time

                # The spending limit applies per transaction.
                PER_TRANSACTION: :per_transaction

                # The spending limit applies per day. Resets nightly at midnight UTC.
                PER_DAY: :per_day

                # The spending limit applies per week. Resets weekly on Mondays at midnight UTC.
                PER_WEEK: :per_week

                # The spending limit applies per month. Resets on the first of the month, midnight UTC.
                PER_MONTH: :per_month

                def self?.values: -> ::Array[Increase::Models::CardCreateParams::AuthorizationControls::Usage::MultiUse::SpendingLimit::interval]
              end

              type merchant_category_code = { code: String }

              class MerchantCategoryCode < Increase::Internal::Type::BaseModel
                attr_accessor code: String

                def initialize: (code: String) -> void

                def to_hash: -> { code: String }
              end
            end
          end

          type single_use =
            {
              settlement_amount: Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse::SettlementAmount
            }

          class SingleUse < Increase::Internal::Type::BaseModel
            attr_accessor settlement_amount: Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse::SettlementAmount

            def initialize: (
              settlement_amount: Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse::SettlementAmount
            ) -> void

            def to_hash: -> {
              settlement_amount: Increase::CardCreateParams::AuthorizationControls::Usage::SingleUse::SettlementAmount
            }

            type settlement_amount =
              {
                comparison: Increase::Models::CardCreateParams::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison,
                value: Integer
              }

            class SettlementAmount < Increase::Internal::Type::BaseModel
              attr_accessor comparison: Increase::Models::CardCreateParams::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison

              attr_accessor value: Integer

              def initialize: (
                comparison: Increase::Models::CardCreateParams::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison,
                value: Integer
              ) -> void

              def to_hash: -> {
                comparison: Increase::Models::CardCreateParams::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison,
                value: Integer
              }

              type comparison = :equals | :less_than_or_equals

              module Comparison
                extend Increase::Internal::Type::Enum

                # The settlement amount must be exactly the specified value.
                EQUALS: :equals

                # The settlement amount must be less than or equal to the specified value.
                LESS_THAN_OR_EQUALS: :less_than_or_equals

                def self?.values: -> ::Array[Increase::Models::CardCreateParams::AuthorizationControls::Usage::SingleUse::SettlementAmount::comparison]
              end
            end
          end
        end
      end

      type billing_address =
        {
          city: String,
          :line1 => String,
          postal_code: String,
          state: String,
          :line2 => String
        }

      class BillingAddress < Increase::Internal::Type::BaseModel
        attr_accessor city: String

        attr_accessor line1: String

        attr_accessor postal_code: String

        attr_accessor state: String

        attr_reader line2: String?

        def line2=: (String) -> String

        def initialize: (
          city: String,
          line1: String,
          postal_code: String,
          state: String,
          ?line2: String
        ) -> void

        def to_hash: -> {
          city: String,
          :line1 => String,
          postal_code: String,
          state: String,
          :line2 => String
        }
      end

      type digital_wallet =
        { digital_card_profile_id: String, email: String, phone: String }

      class DigitalWallet < Increase::Internal::Type::BaseModel
        attr_reader digital_card_profile_id: String?

        def digital_card_profile_id=: (String) -> String

        attr_reader email: String?

        def email=: (String) -> String

        attr_reader phone: String?

        def phone=: (String) -> String

        def initialize: (
          ?digital_card_profile_id: String,
          ?email: String,
          ?phone: String
        ) -> void

        def to_hash: -> {
          digital_card_profile_id: String,
          email: String,
          phone: String
        }
      end
    end
  end
end
