module Increase
  module Models
    type declined_transaction_list_response =
      { data: ::Array[Increase::DeclinedTransaction], next_cursor: String? }

    class DeclinedTransactionListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::DeclinedTransaction]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::DeclinedTransaction],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[Increase::DeclinedTransaction],
        next_cursor: String?
      }
    end
  end
end
