module Increase
  module Models
    type declined_transaction_retrieve_params =
      { declined_transaction_id: String }
      & Increase::Internal::Type::request_parameters

    class DeclinedTransactionRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor declined_transaction_id: String

      def initialize: (
        declined_transaction_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        declined_transaction_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
