module Increase
  module Models
    type digital_wallet_token_retrieve_params =
      { digital_wallet_token_id: String }
      & Increase::Internal::Type::request_parameters

    class DigitalWalletTokenRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor digital_wallet_token_id: String

      def initialize: (
        digital_wallet_token_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        digital_wallet_token_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
