module Increase
  module Models
    type entity_list_response =
      { data: ::Array[Increase::Entity], next_cursor: String? }

    class EntityListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::Entity]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::Entity],
        next_cursor: String?
      ) -> void

      def to_hash: -> { data: ::Array[Increase::Entity], next_cursor: String? }
    end
  end
end
