module Increase
  module Models
    type entity_onboarding_session_create_params =
      { program_id: String, redirect_url: String, entity_id: String }
      & Increase::Internal::Type::request_parameters

    class EntityOnboardingSessionCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor program_id: String

      attr_accessor redirect_url: String

      attr_reader entity_id: String?

      def entity_id=: (String) -> String

      def initialize: (
        program_id: String,
        redirect_url: String,
        ?entity_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        program_id: String,
        redirect_url: String,
        entity_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
