module Increase
  module Models
    type export_retrieve_params =
      { export_id: String } & Increase::Internal::Type::request_parameters

    class ExportRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor export_id: String

      def initialize: (
        export_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        export_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
