module Increase
  module Models
    type export_list_response =
      { data: ::Array[Increase::Export], next_cursor: String? }

    class ExportListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::Export]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::Export],
        next_cursor: String?
      ) -> void

      def to_hash: -> { data: ::Array[Increase::Export], next_cursor: String? }
    end
  end
end
