module Increase
  module Models
    type export_create_params =
      {
        category: Increase::Models::ExportCreateParams::category,
        :account_statement_bai2 => Increase::ExportCreateParams::AccountStatementBai2,
        account_statement_ofx: Increase::ExportCreateParams::AccountStatementOfx,
        account_verification_letter: Increase::ExportCreateParams::AccountVerificationLetter,
        balance_csv: Increase::ExportCreateParams::BalanceCsv,
        bookkeeping_account_balance_csv: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv,
        entity_csv: Increase::ExportCreateParams::EntityCsv,
        funding_instructions: Increase::ExportCreateParams::FundingInstructions,
        transaction_csv: Increase::ExportCreateParams::TransactionCsv,
        vendor_csv: Increase::ExportCreateParams::VendorCsv
      }
      & Increase::Internal::Type::request_parameters

    class ExportCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor category: Increase::Models::ExportCreateParams::category

      attr_reader account_statement_bai2: Increase::ExportCreateParams::AccountStatementBai2?

      def account_statement_bai2=: (
        Increase::ExportCreateParams::AccountStatementBai2
      ) -> Increase::ExportCreateParams::AccountStatementBai2

      attr_reader account_statement_ofx: Increase::ExportCreateParams::AccountStatementOfx?

      def account_statement_ofx=: (
        Increase::ExportCreateParams::AccountStatementOfx
      ) -> Increase::ExportCreateParams::AccountStatementOfx

      attr_reader account_verification_letter: Increase::ExportCreateParams::AccountVerificationLetter?

      def account_verification_letter=: (
        Increase::ExportCreateParams::AccountVerificationLetter
      ) -> Increase::ExportCreateParams::AccountVerificationLetter

      attr_reader balance_csv: Increase::ExportCreateParams::BalanceCsv?

      def balance_csv=: (
        Increase::ExportCreateParams::BalanceCsv
      ) -> Increase::ExportCreateParams::BalanceCsv

      attr_reader bookkeeping_account_balance_csv: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv?

      def bookkeeping_account_balance_csv=: (
        Increase::ExportCreateParams::BookkeepingAccountBalanceCsv
      ) -> Increase::ExportCreateParams::BookkeepingAccountBalanceCsv

      attr_reader entity_csv: Increase::ExportCreateParams::EntityCsv?

      def entity_csv=: (
        Increase::ExportCreateParams::EntityCsv
      ) -> Increase::ExportCreateParams::EntityCsv

      attr_reader funding_instructions: Increase::ExportCreateParams::FundingInstructions?

      def funding_instructions=: (
        Increase::ExportCreateParams::FundingInstructions
      ) -> Increase::ExportCreateParams::FundingInstructions

      attr_reader transaction_csv: Increase::ExportCreateParams::TransactionCsv?

      def transaction_csv=: (
        Increase::ExportCreateParams::TransactionCsv
      ) -> Increase::ExportCreateParams::TransactionCsv

      attr_reader vendor_csv: Increase::ExportCreateParams::VendorCsv?

      def vendor_csv=: (
        Increase::ExportCreateParams::VendorCsv
      ) -> Increase::ExportCreateParams::VendorCsv

      def initialize: (
        category: Increase::Models::ExportCreateParams::category,
        ?account_statement_bai2: Increase::ExportCreateParams::AccountStatementBai2,
        ?account_statement_ofx: Increase::ExportCreateParams::AccountStatementOfx,
        ?account_verification_letter: Increase::ExportCreateParams::AccountVerificationLetter,
        ?balance_csv: Increase::ExportCreateParams::BalanceCsv,
        ?bookkeeping_account_balance_csv: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv,
        ?entity_csv: Increase::ExportCreateParams::EntityCsv,
        ?funding_instructions: Increase::ExportCreateParams::FundingInstructions,
        ?transaction_csv: Increase::ExportCreateParams::TransactionCsv,
        ?vendor_csv: Increase::ExportCreateParams::VendorCsv,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        category: Increase::Models::ExportCreateParams::category,
        :account_statement_bai2 => Increase::ExportCreateParams::AccountStatementBai2,
        account_statement_ofx: Increase::ExportCreateParams::AccountStatementOfx,
        account_verification_letter: Increase::ExportCreateParams::AccountVerificationLetter,
        balance_csv: Increase::ExportCreateParams::BalanceCsv,
        bookkeeping_account_balance_csv: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv,
        entity_csv: Increase::ExportCreateParams::EntityCsv,
        funding_instructions: Increase::ExportCreateParams::FundingInstructions,
        transaction_csv: Increase::ExportCreateParams::TransactionCsv,
        vendor_csv: Increase::ExportCreateParams::VendorCsv,
        request_options: Increase::RequestOptions
      }

      type category =
        :account_statement_ofx
        | :account_statement_bai2
        | :transaction_csv
        | :balance_csv
        | :bookkeeping_account_balance_csv
        | :entity_csv
        | :vendor_csv
        | :account_verification_letter
        | :funding_instructions

      module Category
        extend Increase::Internal::Type::Enum

        # Export an Open Financial Exchange (OFX) file of transactions and balances for a given time range and Account.
        ACCOUNT_STATEMENT_OFX: :account_statement_ofx

        # Export a BAI2 file of transactions and balances for a given date and optional Account.
        ACCOUNT_STATEMENT_BAI2: :account_statement_bai2

        # Export a CSV of all transactions for a given time range.
        TRANSACTION_CSV: :transaction_csv

        # Export a CSV of account balances for the dates in a given range.
        BALANCE_CSV: :balance_csv

        # Export a CSV of bookkeeping account balances for the dates in a given range.
        BOOKKEEPING_ACCOUNT_BALANCE_CSV: :bookkeeping_account_balance_csv

        # Export a CSV of entities with a given status.
        ENTITY_CSV: :entity_csv

        # Export a CSV of vendors added to the third-party risk management dashboard.
        VENDOR_CSV: :vendor_csv

        # A PDF of an account verification letter.
        ACCOUNT_VERIFICATION_LETTER: :account_verification_letter

        # A PDF of funding instructions.
        FUNDING_INSTRUCTIONS: :funding_instructions

        def self?.values: -> ::Array[Increase::Models::ExportCreateParams::category]
      end

      type account_statement_bai2 =
        { account_id: String, effective_date: Date, program_id: String }

      class AccountStatementBai2 < Increase::Internal::Type::BaseModel
        attr_reader account_id: String?

        def account_id=: (String) -> String

        attr_reader effective_date: Date?

        def effective_date=: (Date) -> Date

        attr_reader program_id: String?

        def program_id=: (String) -> String

        def initialize: (
          ?account_id: String,
          ?effective_date: Date,
          ?program_id: String
        ) -> void

        def to_hash: -> {
          account_id: String,
          effective_date: Date,
          program_id: String
        }
      end

      type account_statement_ofx =
        {
          account_id: String,
          created_at: Increase::ExportCreateParams::AccountStatementOfx::CreatedAt
        }

      class AccountStatementOfx < Increase::Internal::Type::BaseModel
        attr_accessor account_id: String

        attr_reader created_at: Increase::ExportCreateParams::AccountStatementOfx::CreatedAt?

        def created_at=: (
          Increase::ExportCreateParams::AccountStatementOfx::CreatedAt
        ) -> Increase::ExportCreateParams::AccountStatementOfx::CreatedAt

        def initialize: (
          account_id: String,
          ?created_at: Increase::ExportCreateParams::AccountStatementOfx::CreatedAt
        ) -> void

        def to_hash: -> {
          account_id: String,
          created_at: Increase::ExportCreateParams::AccountStatementOfx::CreatedAt
        }

        type created_at =
          { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_reader after: Time?

          def after=: (Time) -> Time

          attr_reader before: Time?

          def before=: (Time) -> Time

          attr_reader on_or_after: Time?

          def on_or_after=: (Time) -> Time

          attr_reader on_or_before: Time?

          def on_or_before=: (Time) -> Time

          def initialize: (
            ?after: Time,
            ?before: Time,
            ?on_or_after: Time,
            ?on_or_before: Time
          ) -> void

          def to_hash: -> {
            after: Time,
            before: Time,
            on_or_after: Time,
            on_or_before: Time
          }
        end
      end

      type account_verification_letter =
        { account_number_id: String, balance_date: Date }

      class AccountVerificationLetter < Increase::Internal::Type::BaseModel
        attr_accessor account_number_id: String

        attr_reader balance_date: Date?

        def balance_date=: (Date) -> Date

        def initialize: (account_number_id: String, ?balance_date: Date) -> void

        def to_hash: -> { account_number_id: String, balance_date: Date }
      end

      type balance_csv =
        {
          account_id: String,
          created_at: Increase::ExportCreateParams::BalanceCsv::CreatedAt,
          program_id: String
        }

      class BalanceCsv < Increase::Internal::Type::BaseModel
        attr_reader account_id: String?

        def account_id=: (String) -> String

        attr_reader created_at: Increase::ExportCreateParams::BalanceCsv::CreatedAt?

        def created_at=: (
          Increase::ExportCreateParams::BalanceCsv::CreatedAt
        ) -> Increase::ExportCreateParams::BalanceCsv::CreatedAt

        attr_reader program_id: String?

        def program_id=: (String) -> String

        def initialize: (
          ?account_id: String,
          ?created_at: Increase::ExportCreateParams::BalanceCsv::CreatedAt,
          ?program_id: String
        ) -> void

        def to_hash: -> {
          account_id: String,
          created_at: Increase::ExportCreateParams::BalanceCsv::CreatedAt,
          program_id: String
        }

        type created_at =
          { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_reader after: Time?

          def after=: (Time) -> Time

          attr_reader before: Time?

          def before=: (Time) -> Time

          attr_reader on_or_after: Time?

          def on_or_after=: (Time) -> Time

          attr_reader on_or_before: Time?

          def on_or_before=: (Time) -> Time

          def initialize: (
            ?after: Time,
            ?before: Time,
            ?on_or_after: Time,
            ?on_or_before: Time
          ) -> void

          def to_hash: -> {
            after: Time,
            before: Time,
            on_or_after: Time,
            on_or_before: Time
          }
        end
      end

      type bookkeeping_account_balance_csv =
        {
          bookkeeping_account_id: String,
          created_at: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt
        }

      class BookkeepingAccountBalanceCsv < Increase::Internal::Type::BaseModel
        attr_reader bookkeeping_account_id: String?

        def bookkeeping_account_id=: (String) -> String

        attr_reader created_at: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt?

        def created_at=: (
          Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt
        ) -> Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt

        def initialize: (
          ?bookkeeping_account_id: String,
          ?created_at: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt
        ) -> void

        def to_hash: -> {
          bookkeeping_account_id: String,
          created_at: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt
        }

        type created_at =
          { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_reader after: Time?

          def after=: (Time) -> Time

          attr_reader before: Time?

          def before=: (Time) -> Time

          attr_reader on_or_after: Time?

          def on_or_after=: (Time) -> Time

          attr_reader on_or_before: Time?

          def on_or_before=: (Time) -> Time

          def initialize: (
            ?after: Time,
            ?before: Time,
            ?on_or_after: Time,
            ?on_or_before: Time
          ) -> void

          def to_hash: -> {
            after: Time,
            before: Time,
            on_or_after: Time,
            on_or_before: Time
          }
        end
      end

      type entity_csv = {  }

      class EntityCsv < Increase::Internal::Type::BaseModel
        def initialize: -> void

        def to_hash: -> {  }
      end

      type funding_instructions = { account_number_id: String }

      class FundingInstructions < Increase::Internal::Type::BaseModel
        attr_accessor account_number_id: String

        def initialize: (account_number_id: String) -> void

        def to_hash: -> { account_number_id: String }
      end

      type transaction_csv =
        {
          account_id: String,
          created_at: Increase::ExportCreateParams::TransactionCsv::CreatedAt
        }

      class TransactionCsv < Increase::Internal::Type::BaseModel
        attr_reader account_id: String?

        def account_id=: (String) -> String

        attr_reader created_at: Increase::ExportCreateParams::TransactionCsv::CreatedAt?

        def created_at=: (
          Increase::ExportCreateParams::TransactionCsv::CreatedAt
        ) -> Increase::ExportCreateParams::TransactionCsv::CreatedAt

        def initialize: (
          ?account_id: String,
          ?created_at: Increase::ExportCreateParams::TransactionCsv::CreatedAt
        ) -> void

        def to_hash: -> {
          account_id: String,
          created_at: Increase::ExportCreateParams::TransactionCsv::CreatedAt
        }

        type created_at =
          { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_reader after: Time?

          def after=: (Time) -> Time

          attr_reader before: Time?

          def before=: (Time) -> Time

          attr_reader on_or_after: Time?

          def on_or_after=: (Time) -> Time

          attr_reader on_or_before: Time?

          def on_or_before=: (Time) -> Time

          def initialize: (
            ?after: Time,
            ?before: Time,
            ?on_or_after: Time,
            ?on_or_before: Time
          ) -> void

          def to_hash: -> {
            after: Time,
            before: Time,
            on_or_after: Time,
            on_or_before: Time
          }
        end
      end

      type vendor_csv = {  }

      class VendorCsv < Increase::Internal::Type::BaseModel
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
