module Increase
  module Models
    type export =
      {
        id: String,
        :account_statement_bai2 => Increase::Export::AccountStatementBai2?,
        account_statement_ofx: Increase::Export::AccountStatementOfx?,
        account_verification_letter: Increase::Export::AccountVerificationLetter?,
        balance_csv: Increase::Export::BalanceCsv?,
        bookkeeping_account_balance_csv: Increase::Export::BookkeepingAccountBalanceCsv?,
        category: Increase::Models::Export::category,
        created_at: Time,
        dashboard_table_csv: Increase::Export::DashboardTableCsv?,
        entity_csv: Increase::Export::EntityCsv?,
        :form_1099_int => Increase::Export::Form1099Int?,
        :form_1099_misc => Increase::Export::Form1099Misc?,
        funding_instructions: Increase::Export::FundingInstructions?,
        idempotency_key: String?,
        result: Increase::Export::Result?,
        status: Increase::Models::Export::status,
        transaction_csv: Increase::Export::TransactionCsv?,
        type: Increase::Models::Export::type_,
        vendor_csv: Increase::Export::VendorCsv?
      }

    class Export < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor account_statement_bai2: Increase::Export::AccountStatementBai2?

      attr_accessor account_statement_ofx: Increase::Export::AccountStatementOfx?

      attr_accessor account_verification_letter: Increase::Export::AccountVerificationLetter?

      attr_accessor balance_csv: Increase::Export::BalanceCsv?

      attr_accessor bookkeeping_account_balance_csv: Increase::Export::BookkeepingAccountBalanceCsv?

      attr_accessor category: Increase::Models::Export::category

      attr_accessor created_at: Time

      attr_accessor dashboard_table_csv: Increase::Export::DashboardTableCsv?

      attr_accessor entity_csv: Increase::Export::EntityCsv?

      attr_accessor form_1099_int: Increase::Export::Form1099Int?

      attr_accessor form_1099_misc: Increase::Export::Form1099Misc?

      attr_accessor funding_instructions: Increase::Export::FundingInstructions?

      attr_accessor idempotency_key: String?

      attr_accessor result: Increase::Export::Result?

      attr_accessor status: Increase::Models::Export::status

      attr_accessor transaction_csv: Increase::Export::TransactionCsv?

      attr_accessor type: Increase::Models::Export::type_

      attr_accessor vendor_csv: Increase::Export::VendorCsv?

      def initialize: (
        id: String,
        account_statement_bai2: Increase::Export::AccountStatementBai2?,
        account_statement_ofx: Increase::Export::AccountStatementOfx?,
        account_verification_letter: Increase::Export::AccountVerificationLetter?,
        balance_csv: Increase::Export::BalanceCsv?,
        bookkeeping_account_balance_csv: Increase::Export::BookkeepingAccountBalanceCsv?,
        category: Increase::Models::Export::category,
        created_at: Time,
        dashboard_table_csv: Increase::Export::DashboardTableCsv?,
        entity_csv: Increase::Export::EntityCsv?,
        form_1099_int: Increase::Export::Form1099Int?,
        form_1099_misc: Increase::Export::Form1099Misc?,
        funding_instructions: Increase::Export::FundingInstructions?,
        idempotency_key: String?,
        result: Increase::Export::Result?,
        status: Increase::Models::Export::status,
        transaction_csv: Increase::Export::TransactionCsv?,
        type: Increase::Models::Export::type_,
        vendor_csv: Increase::Export::VendorCsv?
      ) -> void

      def to_hash: -> {
        id: String,
        :account_statement_bai2 => Increase::Export::AccountStatementBai2?,
        account_statement_ofx: Increase::Export::AccountStatementOfx?,
        account_verification_letter: Increase::Export::AccountVerificationLetter?,
        balance_csv: Increase::Export::BalanceCsv?,
        bookkeeping_account_balance_csv: Increase::Export::BookkeepingAccountBalanceCsv?,
        category: Increase::Models::Export::category,
        created_at: Time,
        dashboard_table_csv: Increase::Export::DashboardTableCsv?,
        entity_csv: Increase::Export::EntityCsv?,
        :form_1099_int => Increase::Export::Form1099Int?,
        :form_1099_misc => Increase::Export::Form1099Misc?,
        funding_instructions: Increase::Export::FundingInstructions?,
        idempotency_key: String?,
        result: Increase::Export::Result?,
        status: Increase::Models::Export::status,
        transaction_csv: Increase::Export::TransactionCsv?,
        type: Increase::Models::Export::type_,
        vendor_csv: Increase::Export::VendorCsv?
      }

      type account_statement_bai2 =
        { account_id: String?, effective_date: Date?, program_id: String? }

      class AccountStatementBai2 < Increase::Internal::Type::BaseModel
        attr_accessor account_id: String?

        attr_accessor effective_date: Date?

        attr_accessor program_id: String?

        def initialize: (
          account_id: String?,
          effective_date: Date?,
          program_id: String?
        ) -> void

        def to_hash: -> {
          account_id: String?,
          effective_date: Date?,
          program_id: String?
        }
      end

      type account_statement_ofx =
        {
          account_id: String,
          created_at: Increase::Export::AccountStatementOfx::CreatedAt?
        }

      class AccountStatementOfx < Increase::Internal::Type::BaseModel
        attr_accessor account_id: String

        attr_accessor created_at: Increase::Export::AccountStatementOfx::CreatedAt?

        def initialize: (
          account_id: String,
          created_at: Increase::Export::AccountStatementOfx::CreatedAt?
        ) -> void

        def to_hash: -> {
          account_id: String,
          created_at: Increase::Export::AccountStatementOfx::CreatedAt?
        }

        type created_at = { after: Time?, before: Time? }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_accessor after: Time?

          attr_accessor before: Time?

          def initialize: (after: Time?, before: Time?) -> void

          def to_hash: -> { after: Time?, before: Time? }
        end
      end

      type account_verification_letter =
        { account_number_id: String, balance_date: Date? }

      class AccountVerificationLetter < Increase::Internal::Type::BaseModel
        attr_accessor account_number_id: String

        attr_accessor balance_date: Date?

        def initialize: (account_number_id: String, balance_date: Date?) -> void

        def to_hash: -> { account_number_id: String, balance_date: Date? }
      end

      type balance_csv =
        {
          account_id: String?,
          created_at: Increase::Export::BalanceCsv::CreatedAt?
        }

      class BalanceCsv < Increase::Internal::Type::BaseModel
        attr_accessor account_id: String?

        attr_accessor created_at: Increase::Export::BalanceCsv::CreatedAt?

        def initialize: (
          account_id: String?,
          created_at: Increase::Export::BalanceCsv::CreatedAt?
        ) -> void

        def to_hash: -> {
          account_id: String?,
          created_at: Increase::Export::BalanceCsv::CreatedAt?
        }

        type created_at = { after: Time?, before: Time? }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_accessor after: Time?

          attr_accessor before: Time?

          def initialize: (after: Time?, before: Time?) -> void

          def to_hash: -> { after: Time?, before: Time? }
        end
      end

      type bookkeeping_account_balance_csv =
        {
          bookkeeping_account_id: String?,
          created_at: Increase::Export::BookkeepingAccountBalanceCsv::CreatedAt?
        }

      class BookkeepingAccountBalanceCsv < Increase::Internal::Type::BaseModel
        attr_accessor bookkeeping_account_id: String?

        attr_accessor created_at: Increase::Export::BookkeepingAccountBalanceCsv::CreatedAt?

        def initialize: (
          bookkeeping_account_id: String?,
          created_at: Increase::Export::BookkeepingAccountBalanceCsv::CreatedAt?
        ) -> void

        def to_hash: -> {
          bookkeeping_account_id: String?,
          created_at: Increase::Export::BookkeepingAccountBalanceCsv::CreatedAt?
        }

        type created_at = { after: Time?, before: Time? }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_accessor after: Time?

          attr_accessor before: Time?

          def initialize: (after: Time?, before: Time?) -> void

          def to_hash: -> { after: Time?, before: Time? }
        end
      end

      type category =
        :account_statement_ofx
        | :account_statement_bai2
        | :transaction_csv
        | :balance_csv
        | :bookkeeping_account_balance_csv
        | :entity_csv
        | :vendor_csv
        | :dashboard_table_csv
        | :account_verification_letter
        | :funding_instructions
        | :form_1099_int
        | :form_1099_misc

      module Category
        extend Increase::Internal::Type::Enum

        # Export an Open Financial Exchange (OFX) file of transactions and balances for a given time range and Account.
        ACCOUNT_STATEMENT_OFX: :account_statement_ofx

        # Export a BAI2 file of transactions and balances for a given date and optional Account.
        ACCOUNT_STATEMENT_BAI2: :account_statement_bai2

        # Export a CSV of all transactions for a given time range.
        TRANSACTION_CSV: :transaction_csv

        # Export a CSV of account balances for the dates in a given range.
        BALANCE_CSV: :balance_csv

        # Export a CSV of bookkeeping account balances for the dates in a given range.
        BOOKKEEPING_ACCOUNT_BALANCE_CSV: :bookkeeping_account_balance_csv

        # Export a CSV of entities with a given status.
        ENTITY_CSV: :entity_csv

        # Export a CSV of vendors added to the third-party risk management dashboard.
        VENDOR_CSV: :vendor_csv

        # Certain dashboard tables are available as CSV exports. This export cannot be created via the API.
        DASHBOARD_TABLE_CSV: :dashboard_table_csv

        # A PDF of an account verification letter.
        ACCOUNT_VERIFICATION_LETTER: :account_verification_letter

        # A PDF of funding instructions.
        FUNDING_INSTRUCTIONS: :funding_instructions

        # A PDF of an Internal Revenue Service Form 1099-INT.
        FORM_1099_INT: :form_1099_int

        # A PDF of an Internal Revenue Service Form 1099-MISC.
        FORM_1099_MISC: :form_1099_misc

        def self?.values: -> ::Array[Increase::Models::Export::category]
      end

      type dashboard_table_csv = {  }

      class DashboardTableCsv < Increase::Internal::Type::BaseModel
        def initialize: -> void

        def to_hash: -> {  }
      end

      type entity_csv = {  }

      class EntityCsv < Increase::Internal::Type::BaseModel
        def initialize: -> void

        def to_hash: -> {  }
      end

      type form1099_int =
        {
          account_id: String,
          corrected: bool,
          description: String,
          year: Integer
        }

      class Form1099Int < Increase::Internal::Type::BaseModel
        attr_accessor account_id: String

        attr_accessor corrected: bool

        attr_accessor description: String

        attr_accessor year: Integer

        def initialize: (
          account_id: String,
          corrected: bool,
          description: String,
          year: Integer
        ) -> void

        def to_hash: -> {
          account_id: String,
          corrected: bool,
          description: String,
          year: Integer
        }
      end

      type form1099_misc =
        { account_id: String, corrected: bool, year: Integer }

      class Form1099Misc < Increase::Internal::Type::BaseModel
        attr_accessor account_id: String

        attr_accessor corrected: bool

        attr_accessor year: Integer

        def initialize: (
          account_id: String,
          corrected: bool,
          year: Integer
        ) -> void

        def to_hash: -> { account_id: String, corrected: bool, year: Integer }
      end

      type funding_instructions = { account_number_id: String }

      class FundingInstructions < Increase::Internal::Type::BaseModel
        attr_accessor account_number_id: String

        def initialize: (account_number_id: String) -> void

        def to_hash: -> { account_number_id: String }
      end

      type result = { file_id: String }

      class Result < Increase::Internal::Type::BaseModel
        attr_accessor file_id: String

        def initialize: (file_id: String) -> void

        def to_hash: -> { file_id: String }
      end

      type status = :pending | :complete | :failed

      module Status
        extend Increase::Internal::Type::Enum

        # Increase is generating the export.
        PENDING: :pending

        # The export has been successfully generated.
        COMPLETE: :complete

        # The export failed to generate. Increase will reach out to you to resolve the issue.
        FAILED: :failed

        def self?.values: -> ::Array[Increase::Models::Export::status]
      end

      type transaction_csv =
        {
          account_id: String?,
          created_at: Increase::Export::TransactionCsv::CreatedAt?
        }

      class TransactionCsv < Increase::Internal::Type::BaseModel
        attr_accessor account_id: String?

        attr_accessor created_at: Increase::Export::TransactionCsv::CreatedAt?

        def initialize: (
          account_id: String?,
          created_at: Increase::Export::TransactionCsv::CreatedAt?
        ) -> void

        def to_hash: -> {
          account_id: String?,
          created_at: Increase::Export::TransactionCsv::CreatedAt?
        }

        type created_at = { after: Time?, before: Time? }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_accessor after: Time?

          attr_accessor before: Time?

          def initialize: (after: Time?, before: Time?) -> void

          def to_hash: -> { after: Time?, before: Time? }
        end
      end

      type type_ = :export

      module Type
        extend Increase::Internal::Type::Enum

        EXPORT: :export

        def self?.values: -> ::Array[Increase::Models::Export::type_]
      end

      type vendor_csv = {  }

      class VendorCsv < Increase::Internal::Type::BaseModel
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
