module Increase
  module Models
    type group =
      { id: String, created_at: Time, type: Increase::Models::Group::type_ }

    class Group < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor type: Increase::Models::Group::type_

      def initialize: (
        id: String,
        created_at: Time,
        type: Increase::Models::Group::type_
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        type: Increase::Models::Group::type_
      }

      type type_ = :group

      module Type
        extend Increase::Internal::Type::Enum

        GROUP: :group

        def self?.values: -> ::Array[Increase::Models::Group::type_]
      end
    end
  end
end
