module Increase
  module Models
    type inbound_real_time_payments_transfer_retrieve_params =
      { inbound_real_time_payments_transfer_id: String }
      & Increase::Internal::Type::request_parameters

    class InboundRealTimePaymentsTransferRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor inbound_real_time_payments_transfer_id: String

      def initialize: (
        inbound_real_time_payments_transfer_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        inbound_real_time_payments_transfer_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
