module Increase
  module Models
    type intrafi_exclusion_create_params =
      { entity_id: String, fdic_certificate_number: String }
      & Increase::Internal::Type::request_parameters

    class IntrafiExclusionCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor entity_id: String

      attr_accessor fdic_certificate_number: String

      def initialize: (
        entity_id: String,
        fdic_certificate_number: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        entity_id: String,
        fdic_certificate_number: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
