module Increase
  module Models
    type lockbox_update_params =
      {
        check_deposit_behavior: Increase::Models::LockboxUpdateParams::check_deposit_behavior,
        description: String,
        recipient_name: String
      }
      & Increase::Internal::Type::request_parameters

    class LockboxUpdateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader check_deposit_behavior: Increase::Models::LockboxUpdateParams::check_deposit_behavior?

      def check_deposit_behavior=: (
        Increase::Models::LockboxUpdateParams::check_deposit_behavior
      ) -> Increase::Models::LockboxUpdateParams::check_deposit_behavior

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader recipient_name: String?

      def recipient_name=: (String) -> String

      def initialize: (
        ?check_deposit_behavior: Increase::Models::LockboxUpdateParams::check_deposit_behavior,
        ?description: String,
        ?recipient_name: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        check_deposit_behavior: Increase::Models::LockboxUpdateParams::check_deposit_behavior,
        description: String,
        recipient_name: String,
        request_options: Increase::RequestOptions
      }

      type check_deposit_behavior = :enabled | :disabled | :pend_for_processing

      module CheckDepositBehavior
        extend Increase::Internal::Type::Enum

        # Checks mailed to this Lockbox will be deposited.
        ENABLED: :enabled

        # Checks mailed to this Lockbox will not be deposited.
        DISABLED: :disabled

        # Checks mailed to this Lockbox will be pending until actioned.
        PEND_FOR_PROCESSING: :pend_for_processing

        def self?.values: -> ::Array[Increase::Models::LockboxUpdateParams::check_deposit_behavior]
      end
    end
  end
end
