module Increase
  module Models
    type lockbox_list_response =
      { data: ::Array[Increase::Lockbox], next_cursor: String? }

    class LockboxListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::Lockbox]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::Lockbox],
        next_cursor: String?
      ) -> void

      def to_hash: -> { data: ::Array[Increase::Lockbox], next_cursor: String? }
    end
  end
end
