module Increase
  module Models
    type oauth_connection_retrieve_params =
      { oauth_connection_id: String }
      & Increase::Internal::Type::request_parameters

    class OAuthConnectionRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor oauth_connection_id: String

      def initialize: (
        oauth_connection_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        oauth_connection_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
