module Increase
  module Models
    type oauth_application_list_response =
      { data: ::Array[Increase::OAuthApplication], next_cursor: String? }

    class OAuthApplicationListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::OAuthApplication]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::OAuthApplication],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[Increase::OAuthApplication],
        next_cursor: String?
      }
    end
  end
end
