module Increase
  module Models
    type oauth_connection_list_response =
      { data: ::Array[Increase::OAuthConnection], next_cursor: String? }

    class OAuthConnectionListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::OAuthConnection]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::OAuthConnection],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[Increase::OAuthConnection],
        next_cursor: String?
      }
    end
  end
end
