module Increase
  module Models
    type physical_card_profile_list_response =
      { data: ::Array[Increase::PhysicalCardProfile], next_cursor: String? }

    class PhysicalCardProfileListResponse < Increase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Increase::PhysicalCardProfile]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Increase::PhysicalCardProfile],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[Increase::PhysicalCardProfile],
        next_cursor: String?
      }
    end
  end
end
