module Increase
  module Models
    type program_retrieve_params =
      { program_id: String } & Increase::Internal::Type::request_parameters

    class ProgramRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor program_id: String

      def initialize: (
        program_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        program_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
