module Increase
  module Models
    type real_time_payments_transfer_approve_params =
      { real_time_payments_transfer_id: String }
      & Increase::Internal::Type::request_parameters

    class RealTimePaymentsTransferApproveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor real_time_payments_transfer_id: String

      def initialize: (
        real_time_payments_transfer_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        real_time_payments_transfer_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
