module Increase
  module Models
    type swift_transfer_retrieve_params =
      { swift_transfer_id: String }
      & Increase::Internal::Type::request_parameters

    class SwiftTransferRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor swift_transfer_id: String

      def initialize: (
        swift_transfer_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        swift_transfer_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
