module Increase
  module Models
    type wire_transfer =
      {
        id: String,
        account_id: String,
        account_number: String,
        amount: Integer,
        approval: Increase::WireTransfer::Approval?,
        cancellation: Increase::WireTransfer::Cancellation?,
        created_at: Time,
        created_by: Increase::WireTransfer::CreatedBy?,
        creditor: Increase::WireTransfer::Creditor?,
        currency: Increase::Models::WireTransfer::currency,
        debtor: Increase::WireTransfer::Debtor?,
        external_account_id: String?,
        idempotency_key: String?,
        inbound_wire_drawdown_request_id: String?,
        network: Increase::Models::WireTransfer::network,
        pending_transaction_id: String?,
        remittance: Increase::WireTransfer::Remittance?,
        reversal: Increase::WireTransfer::Reversal?,
        routing_number: String,
        source_account_number_id: String?,
        status: Increase::Models::WireTransfer::status,
        submission: Increase::WireTransfer::Submission?,
        transaction_id: String?,
        type: Increase::Models::WireTransfer::type_
      }

    class WireTransfer < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor account_id: String

      attr_accessor account_number: String

      attr_accessor amount: Integer

      attr_accessor approval: Increase::WireTransfer::Approval?

      attr_accessor cancellation: Increase::WireTransfer::Cancellation?

      attr_accessor created_at: Time

      attr_accessor created_by: Increase::WireTransfer::CreatedBy?

      attr_accessor creditor: Increase::WireTransfer::Creditor?

      attr_accessor currency: Increase::Models::WireTransfer::currency

      attr_accessor debtor: Increase::WireTransfer::Debtor?

      attr_accessor external_account_id: String?

      attr_accessor idempotency_key: String?

      attr_accessor inbound_wire_drawdown_request_id: String?

      attr_accessor network: Increase::Models::WireTransfer::network

      attr_accessor pending_transaction_id: String?

      attr_accessor remittance: Increase::WireTransfer::Remittance?

      attr_accessor reversal: Increase::WireTransfer::Reversal?

      attr_accessor routing_number: String

      attr_accessor source_account_number_id: String?

      attr_accessor status: Increase::Models::WireTransfer::status

      attr_accessor submission: Increase::WireTransfer::Submission?

      attr_accessor transaction_id: String?

      attr_accessor type: Increase::Models::WireTransfer::type_

      def initialize: (
        id: String,
        account_id: String,
        account_number: String,
        amount: Integer,
        approval: Increase::WireTransfer::Approval?,
        cancellation: Increase::WireTransfer::Cancellation?,
        created_at: Time,
        created_by: Increase::WireTransfer::CreatedBy?,
        creditor: Increase::WireTransfer::Creditor?,
        currency: Increase::Models::WireTransfer::currency,
        debtor: Increase::WireTransfer::Debtor?,
        external_account_id: String?,
        idempotency_key: String?,
        inbound_wire_drawdown_request_id: String?,
        network: Increase::Models::WireTransfer::network,
        pending_transaction_id: String?,
        remittance: Increase::WireTransfer::Remittance?,
        reversal: Increase::WireTransfer::Reversal?,
        routing_number: String,
        source_account_number_id: String?,
        status: Increase::Models::WireTransfer::status,
        submission: Increase::WireTransfer::Submission?,
        transaction_id: String?,
        type: Increase::Models::WireTransfer::type_
      ) -> void

      def to_hash: -> {
        id: String,
        account_id: String,
        account_number: String,
        amount: Integer,
        approval: Increase::WireTransfer::Approval?,
        cancellation: Increase::WireTransfer::Cancellation?,
        created_at: Time,
        created_by: Increase::WireTransfer::CreatedBy?,
        creditor: Increase::WireTransfer::Creditor?,
        currency: Increase::Models::WireTransfer::currency,
        debtor: Increase::WireTransfer::Debtor?,
        external_account_id: String?,
        idempotency_key: String?,
        inbound_wire_drawdown_request_id: String?,
        network: Increase::Models::WireTransfer::network,
        pending_transaction_id: String?,
        remittance: Increase::WireTransfer::Remittance?,
        reversal: Increase::WireTransfer::Reversal?,
        routing_number: String,
        source_account_number_id: String?,
        status: Increase::Models::WireTransfer::status,
        submission: Increase::WireTransfer::Submission?,
        transaction_id: String?,
        type: Increase::Models::WireTransfer::type_
      }

      type approval = { approved_at: Time, approved_by: String? }

      class Approval < Increase::Internal::Type::BaseModel
        attr_accessor approved_at: Time

        attr_accessor approved_by: String?

        def initialize: (approved_at: Time, approved_by: String?) -> void

        def to_hash: -> { approved_at: Time, approved_by: String? }
      end

      type cancellation = { canceled_at: Time, canceled_by: String? }

      class Cancellation < Increase::Internal::Type::BaseModel
        attr_accessor canceled_at: Time

        attr_accessor canceled_by: String?

        def initialize: (canceled_at: Time, canceled_by: String?) -> void

        def to_hash: -> { canceled_at: Time, canceled_by: String? }
      end

      type created_by =
        {
          api_key: Increase::WireTransfer::CreatedBy::APIKey?,
          category: Increase::Models::WireTransfer::CreatedBy::category,
          oauth_application: Increase::WireTransfer::CreatedBy::OAuthApplication?,
          user: Increase::WireTransfer::CreatedBy::User?
        }

      class CreatedBy < Increase::Internal::Type::BaseModel
        attr_accessor api_key: Increase::WireTransfer::CreatedBy::APIKey?

        attr_accessor category: Increase::Models::WireTransfer::CreatedBy::category

        attr_accessor oauth_application: Increase::WireTransfer::CreatedBy::OAuthApplication?

        attr_accessor user: Increase::WireTransfer::CreatedBy::User?

        def initialize: (
          api_key: Increase::WireTransfer::CreatedBy::APIKey?,
          category: Increase::Models::WireTransfer::CreatedBy::category,
          oauth_application: Increase::WireTransfer::CreatedBy::OAuthApplication?,
          user: Increase::WireTransfer::CreatedBy::User?
        ) -> void

        def to_hash: -> {
          api_key: Increase::WireTransfer::CreatedBy::APIKey?,
          category: Increase::Models::WireTransfer::CreatedBy::category,
          oauth_application: Increase::WireTransfer::CreatedBy::OAuthApplication?,
          user: Increase::WireTransfer::CreatedBy::User?
        }

        type api_key = { description: String? }

        class APIKey < Increase::Internal::Type::BaseModel
          attr_accessor description: String?

          def initialize: (description: String?) -> void

          def to_hash: -> { description: String? }
        end

        type category = :api_key | :oauth_application | :user

        module Category
          extend Increase::Internal::Type::Enum

          # An API key. Details will be under the `api_key` object.
          API_KEY: :api_key

          # An OAuth application you connected to Increase. Details will be under the `oauth_application` object.
          OAUTH_APPLICATION: :oauth_application

          # A User in the Increase dashboard. Details will be under the `user` object.
          USER: :user

          def self?.values: -> ::Array[Increase::Models::WireTransfer::CreatedBy::category]
        end

        type oauth_application = { name: String }

        class OAuthApplication < Increase::Internal::Type::BaseModel
          attr_accessor name: String

          def initialize: (name: String) -> void

          def to_hash: -> { name: String }
        end

        type user = { email: String }

        class User < Increase::Internal::Type::BaseModel
          attr_accessor email: String

          def initialize: (email: String) -> void

          def to_hash: -> { email: String }
        end
      end

      type creditor =
        { address: Increase::WireTransfer::Creditor::Address?, name: String? }

      class Creditor < Increase::Internal::Type::BaseModel
        attr_accessor address: Increase::WireTransfer::Creditor::Address?

        attr_accessor name: String?

        def initialize: (
          address: Increase::WireTransfer::Creditor::Address?,
          name: String?
        ) -> void

        def to_hash: -> {
          address: Increase::WireTransfer::Creditor::Address?,
          name: String?
        }

        type address =
          {
            unstructured: Increase::WireTransfer::Creditor::Address::Unstructured?
          }

        class Address < Increase::Internal::Type::BaseModel
          attr_accessor unstructured: Increase::WireTransfer::Creditor::Address::Unstructured?

          def initialize: (
            unstructured: Increase::WireTransfer::Creditor::Address::Unstructured?
          ) -> void

          def to_hash: -> {
            unstructured: Increase::WireTransfer::Creditor::Address::Unstructured?
          }

          type unstructured =
            { :line1 => String?, :line2 => String?, :line3 => String? }

          class Unstructured < Increase::Internal::Type::BaseModel
            attr_accessor line1: String?

            attr_accessor line2: String?

            attr_accessor line3: String?

            def initialize: (
              line1: String?,
              line2: String?,
              line3: String?
            ) -> void

            def to_hash: -> {
              :line1 => String?,
              :line2 => String?,
              :line3 => String?
            }
          end
        end
      end

      type currency = :CAD | :CHF | :EUR | :GBP | :JPY | :USD

      module Currency
        extend Increase::Internal::Type::Enum

        # Canadian Dollar (CAD)
        CAD: :CAD

        # Swiss Franc (CHF)
        CHF: :CHF

        # Euro (EUR)
        EUR: :EUR

        # British Pound (GBP)
        GBP: :GBP

        # Japanese Yen (JPY)
        JPY: :JPY

        # US Dollar (USD)
        USD: :USD

        def self?.values: -> ::Array[Increase::Models::WireTransfer::currency]
      end

      type debtor =
        { address: Increase::WireTransfer::Debtor::Address?, name: String? }

      class Debtor < Increase::Internal::Type::BaseModel
        attr_accessor address: Increase::WireTransfer::Debtor::Address?

        attr_accessor name: String?

        def initialize: (
          address: Increase::WireTransfer::Debtor::Address?,
          name: String?
        ) -> void

        def to_hash: -> {
          address: Increase::WireTransfer::Debtor::Address?,
          name: String?
        }

        type address =
          {
            unstructured: Increase::WireTransfer::Debtor::Address::Unstructured?
          }

        class Address < Increase::Internal::Type::BaseModel
          attr_accessor unstructured: Increase::WireTransfer::Debtor::Address::Unstructured?

          def initialize: (
            unstructured: Increase::WireTransfer::Debtor::Address::Unstructured?
          ) -> void

          def to_hash: -> {
            unstructured: Increase::WireTransfer::Debtor::Address::Unstructured?
          }

          type unstructured =
            { :line1 => String?, :line2 => String?, :line3 => String? }

          class Unstructured < Increase::Internal::Type::BaseModel
            attr_accessor line1: String?

            attr_accessor line2: String?

            attr_accessor line3: String?

            def initialize: (
              line1: String?,
              line2: String?,
              line3: String?
            ) -> void

            def to_hash: -> {
              :line1 => String?,
              :line2 => String?,
              :line3 => String?
            }
          end
        end
      end

      type network = :wire

      module Network
        extend Increase::Internal::Type::Enum

        WIRE: :wire

        def self?.values: -> ::Array[Increase::Models::WireTransfer::network]
      end

      type remittance =
        {
          category: Increase::Models::WireTransfer::Remittance::category,
          tax: Increase::WireTransfer::Remittance::Tax?,
          unstructured: Increase::WireTransfer::Remittance::Unstructured?
        }

      class Remittance < Increase::Internal::Type::BaseModel
        attr_accessor category: Increase::Models::WireTransfer::Remittance::category

        attr_accessor tax: Increase::WireTransfer::Remittance::Tax?

        attr_accessor unstructured: Increase::WireTransfer::Remittance::Unstructured?

        def initialize: (
          category: Increase::Models::WireTransfer::Remittance::category,
          tax: Increase::WireTransfer::Remittance::Tax?,
          unstructured: Increase::WireTransfer::Remittance::Unstructured?
        ) -> void

        def to_hash: -> {
          category: Increase::Models::WireTransfer::Remittance::category,
          tax: Increase::WireTransfer::Remittance::Tax?,
          unstructured: Increase::WireTransfer::Remittance::Unstructured?
        }

        type category = :unstructured | :tax

        module Category
          extend Increase::Internal::Type::Enum

          # The wire transfer contains unstructured remittance information.
          UNSTRUCTURED: :unstructured

          # The wire transfer is for tax payment purposes to the Internal Revenue Service (IRS).
          TAX: :tax

          def self?.values: -> ::Array[Increase::Models::WireTransfer::Remittance::category]
        end

        type tax =
          { date: Date, identification_number: String, type_code: String }

        class Tax < Increase::Internal::Type::BaseModel
          attr_accessor date: Date

          attr_accessor identification_number: String

          attr_accessor type_code: String

          def initialize: (
            date: Date,
            identification_number: String,
            type_code: String
          ) -> void

          def to_hash: -> {
            date: Date,
            identification_number: String,
            type_code: String
          }
        end

        type unstructured = { message: String }

        class Unstructured < Increase::Internal::Type::BaseModel
          attr_accessor message: String

          def initialize: (message: String) -> void

          def to_hash: -> { message: String }
        end
      end

      type reversal =
        {
          amount: Integer,
          created_at: Time,
          debtor_routing_number: String?,
          description: String,
          input_cycle_date: Date,
          input_message_accountability_data: String,
          input_sequence_number: String,
          input_source: String,
          instruction_identification: String?,
          return_reason_additional_information: String?,
          return_reason_code: String?,
          return_reason_code_description: String?,
          transaction_id: String,
          wire_transfer_id: String
        }

      class Reversal < Increase::Internal::Type::BaseModel
        attr_accessor amount: Integer

        attr_accessor created_at: Time

        attr_accessor debtor_routing_number: String?

        attr_accessor description: String

        attr_accessor input_cycle_date: Date

        attr_accessor input_message_accountability_data: String

        attr_accessor input_sequence_number: String

        attr_accessor input_source: String

        attr_accessor instruction_identification: String?

        attr_accessor return_reason_additional_information: String?

        attr_accessor return_reason_code: String?

        attr_accessor return_reason_code_description: String?

        attr_accessor transaction_id: String

        attr_accessor wire_transfer_id: String

        def initialize: (
          amount: Integer,
          created_at: Time,
          debtor_routing_number: String?,
          description: String,
          input_cycle_date: Date,
          input_message_accountability_data: String,
          input_sequence_number: String,
          input_source: String,
          instruction_identification: String?,
          return_reason_additional_information: String?,
          return_reason_code: String?,
          return_reason_code_description: String?,
          transaction_id: String,
          wire_transfer_id: String
        ) -> void

        def to_hash: -> {
          amount: Integer,
          created_at: Time,
          debtor_routing_number: String?,
          description: String,
          input_cycle_date: Date,
          input_message_accountability_data: String,
          input_sequence_number: String,
          input_source: String,
          instruction_identification: String?,
          return_reason_additional_information: String?,
          return_reason_code: String?,
          return_reason_code_description: String?,
          transaction_id: String,
          wire_transfer_id: String
        }
      end

      type status =
        :pending_approval
        | :canceled
        | :pending_reviewing
        | :rejected
        | :requires_attention
        | :pending_creating
        | :reversed
        | :submitted
        | :complete

      module Status
        extend Increase::Internal::Type::Enum

        # The transfer is pending approval.
        PENDING_APPROVAL: :pending_approval

        # The transfer has been canceled.
        CANCELED: :canceled

        # The transfer is pending review by Increase.
        PENDING_REVIEWING: :pending_reviewing

        # The transfer has been rejected by Increase.
        REJECTED: :rejected

        # The transfer requires attention from an Increase operator.
        REQUIRES_ATTENTION: :requires_attention

        # The transfer is pending creation.
        PENDING_CREATING: :pending_creating

        # The transfer has been reversed.
        REVERSED: :reversed

        # The transfer has been submitted to Fedwire.
        SUBMITTED: :submitted

        # The transfer has been acknowledged by Fedwire and can be considered complete.
        COMPLETE: :complete

        def self?.values: -> ::Array[Increase::Models::WireTransfer::status]
      end

      type submission =
        { input_message_accountability_data: String, submitted_at: Time }

      class Submission < Increase::Internal::Type::BaseModel
        attr_accessor input_message_accountability_data: String

        attr_accessor submitted_at: Time

        def initialize: (
          input_message_accountability_data: String,
          submitted_at: Time
        ) -> void

        def to_hash: -> {
          input_message_accountability_data: String,
          submitted_at: Time
        }
      end

      type type_ = :wire_transfer

      module Type
        extend Increase::Internal::Type::Enum

        WIRE_TRANSFER: :wire_transfer

        def self?.values: -> ::Array[Increase::Models::WireTransfer::type_]
      end
    end
  end
end
