# frozen_string_literal: true

module Increase
  module Resources
    class OAuthTokens
      # Create an OAuth Token
      #
      # @overload create(grant_type:, client_id: nil, client_secret: nil, code: nil, production_token: nil, request_options: {})
      #
      # @param grant_type [Symbol, Increase::Models::OAuthTokenCreateParams::GrantType]
      #   The credential you request in exchange for the code. In Production, this is
      #   always `authorization_code`. In Sandbox, you can pass either enum value.
      #
      # @param client_id [String] The public identifier for your application.
      #
      # @param client_secret [String]
      #   The secret that confirms you own the application. This is redundant given that
      #   the request is made with your API key but it's a required component of OAuth
      #   2.0.
      #
      # @param code [String]
      #   The authorization code generated by the user and given to you as a query
      #   parameter.
      #
      # @param production_token [String]
      #   The production token you want to exchange for a sandbox token. This is only
      #   available in Sandbox. Set `grant_type` to `production_token` to use this
      #   parameter.
      #
      # @param request_options [Increase::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Increase::Models::OAuthToken]
      #
      # @see Increase::Models::OAuthTokenCreateParams
      def create(params)
        parsed, options = Increase::OAuthTokenCreateParams.dump_request(params)
        @client.request(
          method: :post,
          path: "oauth/tokens",
          body: parsed,
          model: Increase::OAuthToken,
          options: options
        )
      end

      # @api private
      #
      # @param client [Increase::Client]
      def initialize(client:)
        @client = client
      end
    end
  end
end
