module Increase
  module Models
    module Simulations
      type ach_transfer_create_notification_of_change_params =
        {
          ach_transfer_id: String,
          corrected_account_funding: Increase::Models::Simulations::ACHTransferCreateNotificationOfChangeParams::corrected_account_funding,
          corrected_account_number: String,
          corrected_individual_id: String,
          corrected_routing_number: String
        }
        & Increase::Internal::Type::request_parameters

      class ACHTransferCreateNotificationOfChangeParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor ach_transfer_id: String

        attr_reader corrected_account_funding: Increase::Models::Simulations::ACHTransferCreateNotificationOfChangeParams::corrected_account_funding?

        def corrected_account_funding=: (
          Increase::Models::Simulations::ACHTransferCreateNotificationOfChangeParams::corrected_account_funding
        ) -> Increase::Models::Simulations::ACHTransferCreateNotificationOfChangeParams::corrected_account_funding

        attr_reader corrected_account_number: String?

        def corrected_account_number=: (String) -> String

        attr_reader corrected_individual_id: String?

        def corrected_individual_id=: (String) -> String

        attr_reader corrected_routing_number: String?

        def corrected_routing_number=: (String) -> String

        def initialize: (
          ach_transfer_id: String,
          ?corrected_account_funding: Increase::Models::Simulations::ACHTransferCreateNotificationOfChangeParams::corrected_account_funding,
          ?corrected_account_number: String,
          ?corrected_individual_id: String,
          ?corrected_routing_number: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> {
          ach_transfer_id: String,
          corrected_account_funding: Increase::Models::Simulations::ACHTransferCreateNotificationOfChangeParams::corrected_account_funding,
          corrected_account_number: String,
          corrected_individual_id: String,
          corrected_routing_number: String,
          request_options: Increase::RequestOptions
        }

        type corrected_account_funding = :checking | :savings | :general_ledger

        module CorrectedAccountFunding
          extend Increase::Internal::Type::Enum

          # A checking account.
          CHECKING: :checking

          # A savings account.
          SAVINGS: :savings

          # A bank's general ledger. Uncommon.
          GENERAL_LEDGER: :general_ledger

          def self?.values: -> ::Array[Increase::Models::Simulations::ACHTransferCreateNotificationOfChangeParams::corrected_account_funding]
        end
      end
    end
  end
end
