module Increase
  module Models
    module Simulations
      type check_deposit_submit_params =
        {
          check_deposit_id: String,
          scan: Increase::Simulations::CheckDepositSubmitParams::Scan
        }
        & Increase::Internal::Type::request_parameters

      class CheckDepositSubmitParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor check_deposit_id: String

        attr_reader scan: Increase::Simulations::CheckDepositSubmitParams::Scan?

        def scan=: (
          Increase::Simulations::CheckDepositSubmitParams::Scan
        ) -> Increase::Simulations::CheckDepositSubmitParams::Scan

        def initialize: (
          check_deposit_id: String,
          ?scan: Increase::Simulations::CheckDepositSubmitParams::Scan,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> {
          check_deposit_id: String,
          scan: Increase::Simulations::CheckDepositSubmitParams::Scan,
          request_options: Increase::RequestOptions
        }

        type scan =
          {
            account_number: String,
            routing_number: String,
            auxiliary_on_us: String
          }

        class Scan < Increase::Internal::Type::BaseModel
          attr_accessor account_number: String

          attr_accessor routing_number: String

          attr_reader auxiliary_on_us: String?

          def auxiliary_on_us=: (String) -> String

          def initialize: (
            account_number: String,
            routing_number: String,
            ?auxiliary_on_us: String
          ) -> void

          def to_hash: -> {
            account_number: String,
            routing_number: String,
            auxiliary_on_us: String
          }
        end
      end
    end
  end
end
