module Increase
  module Models
    module Simulations
      type inbound_wire_drawdown_request_create_params =
        {
          amount: Integer,
          creditor_account_number: String,
          creditor_routing_number: String,
          currency: String,
          recipient_account_number_id: String,
          :creditor_address_line1 => String,
          :creditor_address_line2 => String,
          :creditor_address_line3 => String,
          creditor_name: String,
          debtor_account_number: String,
          :debtor_address_line1 => String,
          :debtor_address_line2 => String,
          :debtor_address_line3 => String,
          debtor_name: String,
          debtor_routing_number: String,
          end_to_end_identification: String,
          instruction_identification: String,
          unique_end_to_end_transaction_reference: String,
          unstructured_remittance_information: String
        }
        & Increase::Internal::Type::request_parameters

      class InboundWireDrawdownRequestCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor amount: Integer

        attr_accessor creditor_account_number: String

        attr_accessor creditor_routing_number: String

        attr_accessor currency: String

        attr_accessor recipient_account_number_id: String

        attr_reader creditor_address_line1: String?

        def creditor_address_line1=: (String) -> String

        attr_reader creditor_address_line2: String?

        def creditor_address_line2=: (String) -> String

        attr_reader creditor_address_line3: String?

        def creditor_address_line3=: (String) -> String

        attr_reader creditor_name: String?

        def creditor_name=: (String) -> String

        attr_reader debtor_account_number: String?

        def debtor_account_number=: (String) -> String

        attr_reader debtor_address_line1: String?

        def debtor_address_line1=: (String) -> String

        attr_reader debtor_address_line2: String?

        def debtor_address_line2=: (String) -> String

        attr_reader debtor_address_line3: String?

        def debtor_address_line3=: (String) -> String

        attr_reader debtor_name: String?

        def debtor_name=: (String) -> String

        attr_reader debtor_routing_number: String?

        def debtor_routing_number=: (String) -> String

        attr_reader end_to_end_identification: String?

        def end_to_end_identification=: (String) -> String

        attr_reader instruction_identification: String?

        def instruction_identification=: (String) -> String

        attr_reader unique_end_to_end_transaction_reference: String?

        def unique_end_to_end_transaction_reference=: (String) -> String

        attr_reader unstructured_remittance_information: String?

        def unstructured_remittance_information=: (String) -> String

        def initialize: (
          amount: Integer,
          creditor_account_number: String,
          creditor_routing_number: String,
          currency: String,
          recipient_account_number_id: String,
          ?creditor_address_line1: String,
          ?creditor_address_line2: String,
          ?creditor_address_line3: String,
          ?creditor_name: String,
          ?debtor_account_number: String,
          ?debtor_address_line1: String,
          ?debtor_address_line2: String,
          ?debtor_address_line3: String,
          ?debtor_name: String,
          ?debtor_routing_number: String,
          ?end_to_end_identification: String,
          ?instruction_identification: String,
          ?unique_end_to_end_transaction_reference: String,
          ?unstructured_remittance_information: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> {
          amount: Integer,
          creditor_account_number: String,
          creditor_routing_number: String,
          currency: String,
          recipient_account_number_id: String,
          :creditor_address_line1 => String,
          :creditor_address_line2 => String,
          :creditor_address_line3 => String,
          creditor_name: String,
          debtor_account_number: String,
          :debtor_address_line1 => String,
          :debtor_address_line2 => String,
          :debtor_address_line3 => String,
          debtor_name: String,
          debtor_routing_number: String,
          end_to_end_identification: String,
          instruction_identification: String,
          unique_end_to_end_transaction_reference: String,
          unstructured_remittance_information: String,
          request_options: Increase::RequestOptions
        }
      end
    end
  end
end
