module Increase
  module Models
    module Simulations
      type pending_transaction_release_inbound_funds_hold_params =
        { pending_transaction_id: String }
        & Increase::Internal::Type::request_parameters

      class PendingTransactionReleaseInboundFundsHoldParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor pending_transaction_id: String

        def initialize: (
          pending_transaction_id: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> {
          pending_transaction_id: String,
          request_options: Increase::RequestOptions
        }
      end
    end
  end
end
