module Increase
  module Models
    module Simulations
      type wire_transfer_submit_params =
        { wire_transfer_id: String }
        & Increase::Internal::Type::request_parameters

      class WireTransferSubmitParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor wire_transfer_id: String

        def initialize: (
          wire_transfer_id: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> {
          wire_transfer_id: String,
          request_options: Increase::RequestOptions
        }
      end
    end
  end
end
